///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createInfosGenerales3 recording.
    /// </summary>
    [TestModule("f7578754-fd9b-4f4e-96e2-1566a9934db7", ModuleType.Recording, 1)]
    public partial class createInfosGenerales3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createInfosGenerales3 instance = new createInfosGenerales3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createInfosGenerales3()
        {
            nomFournisseur = "119;9";
            nomClient = "178;8";
            conjunctionTicket = "{NumPad1}";
            ex2 = "{NumPad1}";
            ex3 = "{NumPad1}";
            observations = "{NumPad1}";
            docEchanges = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createInfosGenerales3 Instance
        {
            get { return instance; }
        }

#region Variables

        string _nomFournisseur;

        /// <summary>
        /// Gets or sets the value of variable nomFournisseur.
        /// </summary>
        [TestVariable("429ff8ea-ae48-439e-a084-a0f00570e7a8")]
        public string nomFournisseur
        {
            get { return _nomFournisseur; }
            set { _nomFournisseur = value; }
        }

        string _nomClient;

        /// <summary>
        /// Gets or sets the value of variable nomClient.
        /// </summary>
        [TestVariable("b8e792d7-873a-497f-9146-818879aa1e85")]
        public string nomClient
        {
            get { return _nomClient; }
            set { _nomClient = value; }
        }

        string _conjunctionTicket;

        /// <summary>
        /// Gets or sets the value of variable conjunctionTicket.
        /// </summary>
        [TestVariable("404d2180-f25b-4325-8cc4-feaa0da92c56")]
        public string conjunctionTicket
        {
            get { return _conjunctionTicket; }
            set { _conjunctionTicket = value; }
        }

        string _ex2;

        /// <summary>
        /// Gets or sets the value of variable ex2.
        /// </summary>
        [TestVariable("788eb9b6-e959-451f-a1ce-ab0dd5e8e58e")]
        public string ex2
        {
            get { return _ex2; }
            set { _ex2 = value; }
        }

        string _ex3;

        /// <summary>
        /// Gets or sets the value of variable ex3.
        /// </summary>
        [TestVariable("897bba0d-0e71-42b2-b658-d3710b97851c")]
        public string ex3
        {
            get { return _ex3; }
            set { _ex3 = value; }
        }

        string _observations;

        /// <summary>
        /// Gets or sets the value of variable observations.
        /// </summary>
        [TestVariable("64c5e4cb-9d5f-4a17-9d66-b1a0f505123e")]
        public string observations
        {
            get { return _observations; }
            set { _observations = value; }
        }

        string _docEchanges;

        /// <summary>
        /// Gets or sets the value of variable docEchanges.
        /// </summary>
        [TestVariable("2985a3f8-3eea-407b-9f64-b44ef12b99d5")]
        public string docEchanges
        {
            get { return _docEchanges; }
            set { _docEchanges = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable etk.
        /// </summary>
        [TestVariable("8be69e47-e06f-4ff6-be34-199126f3385a")]
        public string etk
        {
            get { return repo.etk; }
            set { repo.etk = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageInfosGenerales' at 35;10.", repo.FrmSglBooking.TabPageInfosGeneralesInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageInfosGenerales.Click("35;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 4;7.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("4;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at 165;7.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(2));
            repo.Bora.ScrollingRegion.Click("165;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Veuillez sélectionner le Produit.') on item 'BoraMessageBox.VeuillezSelectionnerLeProduit'.", repo.BoraMessageBox.VeuillezSelectionnerLeProduitInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.BoraMessageBox.VeuillezSelectionnerLeProduitInfo, "Text", "Veuillez sélectionner le Produit.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 40;8.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(4));
            repo.BoraMessageBox.ButtonOk.Click("40;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 46;8.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(5));
            //repo.BoraMessageBox.ButtonOk.Click("46;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 19;13.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.BtnOk.Click("19;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Veuillez sélectionner le Fournisseur.') on item 'BoraMessageBox.VeuillezSelectionnerLeProduit'.", repo.BoraMessageBox.VeuillezSelectionnerLeProduitInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.BoraMessageBox.VeuillezSelectionnerLeProduitInfo, "Text", "Veuillez sélectionner le Fournisseur.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 44;8.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(8));
            repo.BoraMessageBox.ButtonOk.Click("44;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomFournisseur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(9));
            repo.Bora.ScrollingRegion.Click(nomFournisseur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 6;10.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomClient.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(11));
            repo.Bora.ScrollingRegion.Click(nomClient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ChkAirEticket' at 34;10.", repo.FrmSglBooking.UltraTabPageControl1.ChkAirEticketInfo, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl1.ChkAirEticket.Click("34;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None2' at 15;10.", repo.FrmSglBooking.UltraTabPageControl1.None2Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl1.None2.Click("15;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$conjunctionTicket' with focus on 'FrmSglBooking.UltraTabPageControl1.None2'.", repo.FrmSglBooking.UltraTabPageControl1.None2Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl1.None2.PressKeys(conjunctionTicket);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown3' at 17;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown3Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown3.Click("17;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None' at 29;9.", repo.Bora.NoneInfo, new RecordItemIndex(16));
            repo.Bora.None.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ex2' with focus on 'Bora.None'.", repo.Bora.NoneInfo, new RecordItemIndex(17));
            repo.Bora.None.PressKeys(ex2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None1' at 34;11.", repo.Bora.None1Info, new RecordItemIndex(18));
            repo.Bora.None1.Click("34;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ex3' with focus on 'Bora.None1'.", repo.Bora.None1Info, new RecordItemIndex(19));
            repo.Bora.None1.PressKeys(ex3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1' at 68;7.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1.Click("68;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$docEchanges' with focus on 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1.PressKeys(docEchanges);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None3' at 98;11.", repo.FrmSglBooking.UltraTabPageControl1.None3Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl1.None3.Click("98;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$observations' with focus on 'FrmSglBooking.UltraTabPageControl1.None3'.", repo.FrmSglBooking.UltraTabPageControl1.None3Info, new RecordItemIndex(23));
            repo.FrmSglBooking.UltraTabPageControl1.None3.PressKeys(observations);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
