///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createMarge3 recording.
    /// </summary>
    [TestModule("97c43a39-e8c7-4438-9bcc-73625999d036", ModuleType.Recording, 1)]
    public partial class createMarge3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createMarge3 instance = new createMarge3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createMarge3()
        {
            commissionPourcent = "{NumPad1}";
            commission = "{NumPad2}";
            commissionSurPenalite = "{NumPad1}";
            bookingAgent = "147;7";
            ticketingAgent = "122;9";
            demarcheur = "140;9";
            comAgvPartenairePourcent = "{NumPad1}";
            comAgvPartenaire = "{NumPad2}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createMarge3 Instance
        {
            get { return instance; }
        }

#region Variables

        string _commissionPourcent;

        /// <summary>
        /// Gets or sets the value of variable commissionPourcent.
        /// </summary>
        [TestVariable("bf7a3842-5865-440e-9247-916c771db243")]
        public string commissionPourcent
        {
            get { return _commissionPourcent; }
            set { _commissionPourcent = value; }
        }

        string _commission;

        /// <summary>
        /// Gets or sets the value of variable commission.
        /// </summary>
        [TestVariable("29c14e42-5713-44b7-b90a-e843c632a260")]
        public string commission
        {
            get { return _commission; }
            set { _commission = value; }
        }

        string _commissionSurPenalite;

        /// <summary>
        /// Gets or sets the value of variable commissionSurPenalite.
        /// </summary>
        [TestVariable("0e99a8d4-4344-4b48-9307-4f5fd31f718b")]
        public string commissionSurPenalite
        {
            get { return _commissionSurPenalite; }
            set { _commissionSurPenalite = value; }
        }

        string _bookingAgent;

        /// <summary>
        /// Gets or sets the value of variable bookingAgent.
        /// </summary>
        [TestVariable("007fd82a-4c41-4d70-8033-677b6d9043a4")]
        public string bookingAgent
        {
            get { return _bookingAgent; }
            set { _bookingAgent = value; }
        }

        string _ticketingAgent;

        /// <summary>
        /// Gets or sets the value of variable ticketingAgent.
        /// </summary>
        [TestVariable("95e6a3d5-0c08-4b11-8bb9-6675228f5952")]
        public string ticketingAgent
        {
            get { return _ticketingAgent; }
            set { _ticketingAgent = value; }
        }

        string _demarcheur;

        /// <summary>
        /// Gets or sets the value of variable demarcheur.
        /// </summary>
        [TestVariable("794a3192-92e3-4a7d-8601-5e8ba20da556")]
        public string demarcheur
        {
            get { return _demarcheur; }
            set { _demarcheur = value; }
        }

        string _comAgvPartenairePourcent;

        /// <summary>
        /// Gets or sets the value of variable comAgvPartenairePourcent.
        /// </summary>
        [TestVariable("3f20ef2b-a122-47cc-9358-02d507153862")]
        public string comAgvPartenairePourcent
        {
            get { return _comAgvPartenairePourcent; }
            set { _comAgvPartenairePourcent = value; }
        }

        string _comAgvPartenaire;

        /// <summary>
        /// Gets or sets the value of variable comAgvPartenaire.
        /// </summary>
        [TestVariable("6fd6b832-4fae-49ee-a185-e1ef3e7321e4")]
        public string comAgvPartenaire
        {
            get { return _comAgvPartenaire; }
            set { _comAgvPartenaire = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageMarge' at 21;8.", repo.FrmSglBooking.TabPageMargeInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageMarge.Click("21;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None' at 20;9.", repo.FrmSglBooking.UltraTabPageControl5.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl5.None.Click("20;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commissionPourcent' with focus on 'FrmSglBooking.UltraTabPageControl5.None'.", repo.FrmSglBooking.UltraTabPageControl5.NoneInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl5.None.PressKeys(commissionPourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None1' at 77;11.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl5.None1.Click("77;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}' with focus on 'FrmSglBooking.UltraTabPageControl5.None1'.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl5.None1.PressKeys("{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'FrmSglBooking.UltraTabPageControl5.None1'.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl5.None1.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commission' with focus on 'FrmSglBooking.UltraTabPageControl5.None1'.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl5.None1.PressKeys(commission);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None2' at 110;9.", repo.FrmSglBooking.UltraTabPageControl5.None2Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl5.None2.Click("110;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commissionSurPenalite' with focus on 'FrmSglBooking.UltraTabPageControl5.None2'.", repo.FrmSglBooking.UltraTabPageControl5.None2Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl5.None2.PressKeys(commissionSurPenalite);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open' at 5;9.", repo.FrmSglBooking.UltraTabPageControl5.OpenInfo, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl5.Open.Click("5;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $bookingAgent.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(10));
            repo.Bora.ScrollingRegion.Click(bookingAgent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open1' at 6;8.", repo.FrmSglBooking.UltraTabPageControl5.Open1Info, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl5.Open1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $ticketingAgent.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(12));
            repo.Bora.ScrollingRegion.Click(ticketingAgent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open2' at 5;11.", repo.FrmSglBooking.UltraTabPageControl5.Open2Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl5.Open2.Click("5;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $demarcheur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(14));
            repo.Bora.ScrollingRegion.Click(demarcheur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.ButtonDropDown1' at 16;9.", repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown1Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown1.Click("16;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None30' at 18;10.", repo.Bora.None30Info, new RecordItemIndex(16));
            repo.Bora.None30.Click("18;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$comAgvPartenairePourcent' with focus on 'Bora.None30'.", repo.Bora.None30Info, new RecordItemIndex(17));
            repo.Bora.None30.PressKeys(comAgvPartenairePourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None31' at 70;10.", repo.Bora.None31Info, new RecordItemIndex(18));
            repo.Bora.None31.Click("70;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'Bora.None31'.", repo.Bora.None31Info, new RecordItemIndex(19));
            repo.Bora.None31.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$comAgvPartenaire' with focus on 'Bora.None31'.", repo.Bora.None31Info, new RecordItemIndex(20));
            repo.Bora.None31.PressKeys(comAgvPartenaire);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions2' at 105;7.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions2Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions2.Click("105;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
