///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createInfosGenerales recording.
    /// </summary>
    [TestModule("90eb3f3d-f9f4-43fc-9dc1-7453cb79a23d", ModuleType.Recording, 1)]
    public partial class createInfosGenerales : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createInfosGenerales instance = new createInfosGenerales();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createInfosGenerales()
        {
            pointDeVente = "173;8";
            dateReservation = "89;145";
            echeanceFournisseur = "126;145";
            date = "156;144";
            gds = "85;9";
            nomFournisseur = "180;7";
            nomClient = "61;7";
            nomVoyageur = "144;7";
            recordLocator = "{NumPad1}";
            numeroDossier = "171;8";
            numeroBillet = "{NumPad1}";
            conjunctionTicket = "{NumPad1}";
            itineraire = "{NumPad1}";
            ex2 = "{NumPad1}";
            ex3 = "{NumPad1}";
            docEchanges = "{NumPad1}";
            observations = "{NumPad1}";
            retour = "136;144";
            depart = "145;145";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createInfosGenerales Instance
        {
            get { return instance; }
        }

#region Variables

        string _pointDeVente;

        /// <summary>
        /// Gets or sets the value of variable pointDeVente.
        /// </summary>
        [TestVariable("c1a5581e-21bd-43d0-b1c6-1c1d6a7f4722")]
        public string pointDeVente
        {
            get { return _pointDeVente; }
            set { _pointDeVente = value; }
        }

        string _dateReservation;

        /// <summary>
        /// Gets or sets the value of variable dateReservation.
        /// </summary>
        [TestVariable("dbfae433-13af-435f-9e20-60a47791dc1b")]
        public string dateReservation
        {
            get { return _dateReservation; }
            set { _dateReservation = value; }
        }

        string _echeanceFournisseur;

        /// <summary>
        /// Gets or sets the value of variable echeanceFournisseur.
        /// </summary>
        [TestVariable("3a711954-9178-4a6d-bd15-9dd53f4cb16b")]
        public string echeanceFournisseur
        {
            get { return _echeanceFournisseur; }
            set { _echeanceFournisseur = value; }
        }

        string _date;

        /// <summary>
        /// Gets or sets the value of variable date.
        /// </summary>
        [TestVariable("4aadf622-d1a1-4448-acc3-d41af14cdff2")]
        public string date
        {
            get { return _date; }
            set { _date = value; }
        }

        string _gds;

        /// <summary>
        /// Gets or sets the value of variable gds.
        /// </summary>
        [TestVariable("938b8a37-3443-4d9d-9304-4e33430a69bd")]
        public string gds
        {
            get { return _gds; }
            set { _gds = value; }
        }

        string _nomFournisseur;

        /// <summary>
        /// Gets or sets the value of variable nomFournisseur.
        /// </summary>
        [TestVariable("1b91cae4-6d6c-45b7-8a75-653f803cfb81")]
        public string nomFournisseur
        {
            get { return _nomFournisseur; }
            set { _nomFournisseur = value; }
        }

        string _nomClient;

        /// <summary>
        /// Gets or sets the value of variable nomClient.
        /// </summary>
        [TestVariable("36405f02-2413-4b7f-a04e-6c359308c794")]
        public string nomClient
        {
            get { return _nomClient; }
            set { _nomClient = value; }
        }

        string _nomVoyageur;

        /// <summary>
        /// Gets or sets the value of variable nomVoyageur.
        /// </summary>
        [TestVariable("8eb2311b-1c35-4e2f-b418-01dba46ee8e6")]
        public string nomVoyageur
        {
            get { return _nomVoyageur; }
            set { _nomVoyageur = value; }
        }

        string _recordLocator;

        /// <summary>
        /// Gets or sets the value of variable recordLocator.
        /// </summary>
        [TestVariable("8b53e94a-84f0-4f50-b5d9-0d74ba898216")]
        public string recordLocator
        {
            get { return _recordLocator; }
            set { _recordLocator = value; }
        }

        string _numeroDossier;

        /// <summary>
        /// Gets or sets the value of variable numeroDossier.
        /// </summary>
        [TestVariable("c6898042-197c-4dff-b201-0fc1841cadf6")]
        public string numeroDossier
        {
            get { return _numeroDossier; }
            set { _numeroDossier = value; }
        }

        string _numeroBillet;

        /// <summary>
        /// Gets or sets the value of variable numeroBillet.
        /// </summary>
        [TestVariable("021e2182-e059-4ced-90b5-ef6c64ade328")]
        public string numeroBillet
        {
            get { return _numeroBillet; }
            set { _numeroBillet = value; }
        }

        string _conjunctionTicket;

        /// <summary>
        /// Gets or sets the value of variable conjunctionTicket.
        /// </summary>
        [TestVariable("4d42a2dd-1a39-49e9-9a4a-414d4de0d00e")]
        public string conjunctionTicket
        {
            get { return _conjunctionTicket; }
            set { _conjunctionTicket = value; }
        }

        string _itineraire;

        /// <summary>
        /// Gets or sets the value of variable itineraire.
        /// </summary>
        [TestVariable("9c077a21-4d66-4c4c-b261-f92abbcf19f7")]
        public string itineraire
        {
            get { return _itineraire; }
            set { _itineraire = value; }
        }

        string _ex2;

        /// <summary>
        /// Gets or sets the value of variable ex2.
        /// </summary>
        [TestVariable("3dd5c417-8b4c-4ec6-924b-a6e1247a070b")]
        public string ex2
        {
            get { return _ex2; }
            set { _ex2 = value; }
        }

        string _ex3;

        /// <summary>
        /// Gets or sets the value of variable ex3.
        /// </summary>
        [TestVariable("f356a240-f34b-4a3e-8a05-437a77813964")]
        public string ex3
        {
            get { return _ex3; }
            set { _ex3 = value; }
        }

        string _docEchanges;

        /// <summary>
        /// Gets or sets the value of variable docEchanges.
        /// </summary>
        [TestVariable("1b2040e4-cc51-4069-b826-06891ab2362d")]
        public string docEchanges
        {
            get { return _docEchanges; }
            set { _docEchanges = value; }
        }

        string _observations;

        /// <summary>
        /// Gets or sets the value of variable observations.
        /// </summary>
        [TestVariable("82c1baa5-f96d-4a2c-837d-5d49040f9ee2")]
        public string observations
        {
            get { return _observations; }
            set { _observations = value; }
        }

        string _retour;

        /// <summary>
        /// Gets or sets the value of variable retour.
        /// </summary>
        [TestVariable("828feded-c996-4c1e-b8dc-6d60d9288516")]
        public string retour
        {
            get { return _retour; }
            set { _retour = value; }
        }

        string _depart;

        /// <summary>
        /// Gets or sets the value of variable depart.
        /// </summary>
        [TestVariable("0f84554e-81df-4111-976c-bb525c73a661")]
        public string depart
        {
            get { return _depart; }
            set { _depart = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable mode.
        /// </summary>
        [TestVariable("04f1e74b-c091-4b5f-9d3e-29f1257275b2")]
        public string mode
        {
            get { return repo.mode; }
            set { repo.mode = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable transaction.
        /// </summary>
        [TestVariable("5366146b-93e4-41c9-9f3b-d3be42cc08d9")]
        public string transaction
        {
            get { return repo.transaction; }
            set { repo.transaction = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable etk.
        /// </summary>
        [TestVariable("8be69e47-e06f-4ff6-be34-199126f3385a")]
        public string etk
        {
            get { return repo.etk; }
            set { repo.etk = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable typeDocument.
        /// </summary>
        [TestVariable("8f9cb477-522e-47ec-b26b-cacb8aaf1abe")]
        public string typeDocument
        {
            get { return repo.typeDocument; }
            set { repo.typeDocument = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable destination.
        /// </summary>
        [TestVariable("13b82235-a865-4290-9695-2621351de07f")]
        public string destination
        {
            get { return repo.destination; }
            set { repo.destination = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable classeResa.
        /// </summary>
        [TestVariable("61b48ddd-98bf-4f26-bf62-cb1a174cdc87")]
        public string classeResa
        {
            get { return repo.classeResa; }
            set { repo.classeResa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open' at 7;10.", repo.FrmSglBooking.UltraTabPageControl1.OpenInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.UltraTabPageControl1.Open.Click("7;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $pointDeVente.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(1));
            repo.Bora.ScrollingRegion.Click(pointDeVente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open1' at 6;8.", repo.FrmSglBooking.UltraTabPageControl1.Open1Info, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl1.Open1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.DISTRIBUTION' at 89;7.", repo.Bora.DISTRIBUTIONInfo, new RecordItemIndex(3));
            repo.Bora.DISTRIBUTION.Click("89;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open2' at 7;8.", repo.FrmSglBooking.UltraTabPageControl1.Open2Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl1.Open2.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.VENTE' at 55;8.", repo.Bora.VENTEInfo, new RecordItemIndex(5));
            repo.Bora.VENTE.Click("55;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown' at 18;9.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDownInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown.Click("18;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open' at 6;7.", repo.Bora.OpenInfo, new RecordItemIndex(7));
            repo.Bora.Open.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $dateReservation.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(8));
            repo.Bora.MonthDropDownWithUIPermissions.Click(dateReservation);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open1' at 6;10.", repo.Bora.Open1Info, new RecordItemIndex(9));
            repo.Bora.Open1.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $echeanceFournisseur.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(10));
            repo.Bora.MonthDropDownWithUIPermissions.Click(echeanceFournisseur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open3' at 7;8.", repo.FrmSglBooking.UltraTabPageControl1.Open3Info, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl1.Open3.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $date.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(12));
            repo.Bora.MonthDropDownWithUIPermissions.Click(date);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open4' at 8;7.", repo.FrmSglBooking.UltraTabPageControl1.Open4Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl1.Open4.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $gds.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(14));
            repo.Bora.ScrollingRegion.Click(gds);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open5' at 6;7.", repo.FrmSglBooking.UltraTabPageControl1.Open5Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl1.Open5.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomFournisseur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(16));
            repo.Bora.ScrollingRegion.Click(nomFournisseur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open6' at 8;8.", repo.FrmSglBooking.UltraTabPageControl1.Open6Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl1.Open6.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 7;5.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("7;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomClient.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(19));
            repo.Bora.ScrollingRegion.Click(nomClient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown1' at 15;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open2' at 8;7.", repo.Bora.Open2Info, new RecordItemIndex(21));
            repo.Bora.Open2.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open8' at 6;7.", repo.FrmSglBooking.UltraTabPageControl1.Open8Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl1.Open8.Click("6;7");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open8' at 7;7.", repo.FrmSglBooking.UltraTabPageControl1.Open8Info, new RecordItemIndex(23));
            //repo.FrmSglBooking.UltraTabPageControl1.Open8.Click("7;7");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion1' at position from variable $nomVoyageur.", repo.Bora.ScrollingRegion1Info, new RecordItemIndex(24));
            repo.Bora.ScrollingRegion1.Click(nomVoyageur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ContainerTransaction' at 327;218.", repo.FrmSglBooking.UltraTabPageControl1.ContainerTransactionInfo, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl1.ContainerTransaction.Click("327;218");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None' at 159;8.", repo.FrmSglBooking.UltraTabPageControl1.NoneInfo, new RecordItemIndex(26));
            repo.FrmSglBooking.UltraTabPageControl1.None.Click("159;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$recordLocator' with focus on 'FrmSglBooking.UltraTabPageControl1.None'.", repo.FrmSglBooking.UltraTabPageControl1.NoneInfo, new RecordItemIndex(27));
            repo.FrmSglBooking.UltraTabPageControl1.None.PressKeys(recordLocator);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open9' at 6;7.", repo.FrmSglBooking.UltraTabPageControl1.Open9Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl1.Open9.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $numeroDossier.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(29));
            repo.Bora.ScrollingRegion.Click(numeroDossier);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open10' at 7;8.", repo.FrmSglBooking.UltraTabPageControl1.Open10Info, new RecordItemIndex(30));
            repo.FrmSglBooking.UltraTabPageControl1.Open10.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.LblAirCompagnieNom' at 19;6.", repo.FrmSglBooking.UltraTabPageControl1.LblAirCompagnieNomInfo, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl1.LblAirCompagnieNom.Click("19;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ChkAirEticket' at 33;8.", repo.FrmSglBooking.UltraTabPageControl1.ChkAirEticketInfo, new RecordItemIndex(32));
            repo.FrmSglBooking.UltraTabPageControl1.ChkAirEticket.Click("33;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None1' at 13;9.", repo.FrmSglBooking.UltraTabPageControl1.None1Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl1.None1.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroBillet' with focus on 'FrmSglBooking.UltraTabPageControl1.None1'.", repo.FrmSglBooking.UltraTabPageControl1.None1Info, new RecordItemIndex(34));
            repo.FrmSglBooking.UltraTabPageControl1.None1.PressKeys(numeroBillet);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None2' at 16;10.", repo.FrmSglBooking.UltraTabPageControl1.None2Info, new RecordItemIndex(35));
            repo.FrmSglBooking.UltraTabPageControl1.None2.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$conjunctionTicket' with focus on 'FrmSglBooking.UltraTabPageControl1.None2'.", repo.FrmSglBooking.UltraTabPageControl1.None2Info, new RecordItemIndex(36));
            repo.FrmSglBooking.UltraTabPageControl1.None2.PressKeys(conjunctionTicket);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp' at 15;10.", repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXpInfo, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp.Click("15;10");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(38));
            //repo.FrmSglBooking.Self.EnsureVisible();
            //Keyboard.Press(" ");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Cell' at 19;10.", repo.Bora.CellInfo, new RecordItemIndex(39));
            repo.Bora.Cell.Click("19;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown2' at 13;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown2Info, new RecordItemIndex(40));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown2.Click("13;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open3' at 6;9.", repo.Bora.Open3Info, new RecordItemIndex(41));
            repo.Bora.Open3.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItemIN' at 71;8.", repo.Bora.ListItemINInfo, new RecordItemIndex(42));
            repo.Bora.ListItemIN.Click("71;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions' at 28;6.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(43));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions.Click("28;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$itineraire' with focus on 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions.PressKeys(itineraire);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open11' at 6;7.", repo.FrmSglBooking.UltraTabPageControl1.Open11Info, new RecordItemIndex(45));
            repo.FrmSglBooking.UltraTabPageControl1.Open11.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.First' at 102;13.", repo.Bora.FirstInfo, new RecordItemIndex(46));
            repo.Bora.First.Click("102;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown3' at 13;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown3Info, new RecordItemIndex(47));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown3.Click("13;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None' at 28;11.", repo.Bora.NoneInfo, new RecordItemIndex(48));
            repo.Bora.None.Click("28;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ex2' with focus on 'Bora.None'.", repo.Bora.NoneInfo, new RecordItemIndex(49));
            repo.Bora.None.PressKeys(ex2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None1' at 24;11.", repo.Bora.None1Info, new RecordItemIndex(50));
            repo.Bora.None1.Click("24;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ex3' with focus on 'Bora.None1'.", repo.Bora.None1Info, new RecordItemIndex(51));
            repo.Bora.None1.PressKeys(ex3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1' at 38;5.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(52));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1.Click("38;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$docEchanges' with focus on 'FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(53));
            repo.FrmSglBooking.UltraTabPageControl1.EmbeddableTextBoxWithUIPermissions1.PressKeys(docEchanges);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None3' at 57;9.", repo.FrmSglBooking.UltraTabPageControl1.None3Info, new RecordItemIndex(54));
            repo.FrmSglBooking.UltraTabPageControl1.None3.Click("57;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$observations' with focus on 'FrmSglBooking.UltraTabPageControl1.None3'.", repo.FrmSglBooking.UltraTabPageControl1.None3Info, new RecordItemIndex(55));
            repo.FrmSglBooking.UltraTabPageControl1.None3.PressKeys(observations);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open12' at 8;8.", repo.FrmSglBooking.UltraTabPageControl1.Open12Info, new RecordItemIndex(56));
            repo.FrmSglBooking.UltraTabPageControl1.Open12.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $depart.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(57));
            repo.Bora.MonthDropDownWithUIPermissions.Click(depart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open13' at 6;6.", repo.FrmSglBooking.UltraTabPageControl1.Open13Info, new RecordItemIndex(58));
            repo.FrmSglBooking.UltraTabPageControl1.Open13.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $retour.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(59));
            repo.Bora.MonthDropDownWithUIPermissions.Click(retour);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
