///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createNotes recording.
    /// </summary>
    [TestModule("efd2456c-b7a9-46de-a65c-07dae269e362", ModuleType.Recording, 1)]
    public partial class createNotes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createNotes instance = new createNotes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createNotes()
        {
            note = "Note";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createNotes Instance
        {
            get { return instance; }
        }

#region Variables

        string _note;

        /// <summary>
        /// Gets or sets the value of variable note.
        /// </summary>
        [TestVariable("52e8beeb-b1fb-4764-ba94-be37013b88e4")]
        public string note
        {
            get { return _note; }
            set { _note = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.Notes' at 29;10.", repo.FrmSglBooking.NotesInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.Notes.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.None2' at 321;40.", repo.FrmSglBooking.None2Info, new RecordItemIndex(1));
            repo.FrmSglBooking.None2.Click("321;40");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$note' with focus on 'FrmSglBooking.None2'.", repo.FrmSglBooking.None2Info, new RecordItemIndex(2));
            repo.FrmSglBooking.None2.PressKeys(note);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
