///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createUDID recording.
    /// </summary>
    [TestModule("445fe87d-9780-4de9-85ef-7956dedec738", ModuleType.Recording, 1)]
    public partial class createUDID : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createUDID instance = new createUDID();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createUDID()
        {
            champ1 = "{NumPad1}";
            champ2 = "{NumPad1}";
            champ3 = "{NumPad1}";
            champ4 = "{NumPad1}";
            champ5 = "{NumPad1}";
            champ6 = "{NumPad1}";
            champ7 = "{NumPad1}";
            champ8 = "{NumPad1}";
            champ9 = "{NumPad1}";
            champ10 = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createUDID Instance
        {
            get { return instance; }
        }

#region Variables

        string _champ1;

        /// <summary>
        /// Gets or sets the value of variable champ1.
        /// </summary>
        [TestVariable("1a41a0d8-5664-4744-89cc-f7c4c12e348a")]
        public string champ1
        {
            get { return _champ1; }
            set { _champ1 = value; }
        }

        string _champ2;

        /// <summary>
        /// Gets or sets the value of variable champ2.
        /// </summary>
        [TestVariable("730bbd20-193e-4c0e-b22a-dcaeb2cc0507")]
        public string champ2
        {
            get { return _champ2; }
            set { _champ2 = value; }
        }

        string _champ3;

        /// <summary>
        /// Gets or sets the value of variable champ3.
        /// </summary>
        [TestVariable("fb441671-9a97-44c4-a7ba-c58d9bab9b67")]
        public string champ3
        {
            get { return _champ3; }
            set { _champ3 = value; }
        }

        string _champ4;

        /// <summary>
        /// Gets or sets the value of variable champ4.
        /// </summary>
        [TestVariable("5302e43e-d5e3-462a-bbed-11a714d6cceb")]
        public string champ4
        {
            get { return _champ4; }
            set { _champ4 = value; }
        }

        string _champ5;

        /// <summary>
        /// Gets or sets the value of variable champ5.
        /// </summary>
        [TestVariable("a4d358b9-a0c5-4adb-b6cf-640e28fa211a")]
        public string champ5
        {
            get { return _champ5; }
            set { _champ5 = value; }
        }

        string _champ6;

        /// <summary>
        /// Gets or sets the value of variable champ6.
        /// </summary>
        [TestVariable("99491bd5-c17e-4d7a-9004-8510e8fe1b6d")]
        public string champ6
        {
            get { return _champ6; }
            set { _champ6 = value; }
        }

        string _champ7;

        /// <summary>
        /// Gets or sets the value of variable champ7.
        /// </summary>
        [TestVariable("3995cf5a-bdd5-4450-9da9-ea0bb64abd33")]
        public string champ7
        {
            get { return _champ7; }
            set { _champ7 = value; }
        }

        string _champ8;

        /// <summary>
        /// Gets or sets the value of variable champ8.
        /// </summary>
        [TestVariable("333e7ad7-a335-475c-8901-a89c388d1515")]
        public string champ8
        {
            get { return _champ8; }
            set { _champ8 = value; }
        }

        string _champ9;

        /// <summary>
        /// Gets or sets the value of variable champ9.
        /// </summary>
        [TestVariable("438a2227-2b77-4f44-bbda-ee686ecee608")]
        public string champ9
        {
            get { return _champ9; }
            set { _champ9 = value; }
        }

        string _champ10;

        /// <summary>
        /// Gets or sets the value of variable champ10.
        /// </summary>
        [TestVariable("d967c176-d972-4fb5-98ea-e6b6ef97546c")]
        public string champ10
        {
            get { return _champ10; }
            set { _champ10 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UDID' at 29;9.", repo.FrmSglBooking.UDIDInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.UDID.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None3' at 72;10.", repo.FrmSglBooking.UltraTabPageControl3.None3Info, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl3.None3.Click("72;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ1' with focus on 'FrmSglBooking.UltraTabPageControl3.None3'.", repo.FrmSglBooking.UltraTabPageControl3.None3Info, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl3.None3.PressKeys(champ1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None4' at 51;10.", repo.FrmSglBooking.UltraTabPageControl3.None4Info, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl3.None4.Click("51;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ2' with focus on 'FrmSglBooking.UltraTabPageControl3.None4'.", repo.FrmSglBooking.UltraTabPageControl3.None4Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl3.None4.PressKeys(champ2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None5' at 40;9.", repo.FrmSglBooking.UltraTabPageControl3.None5Info, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl3.None5.Click("40;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ3' with focus on 'FrmSglBooking.UltraTabPageControl3.None5'.", repo.FrmSglBooking.UltraTabPageControl3.None5Info, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl3.None5.PressKeys(champ3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None6' at 26;9.", repo.FrmSglBooking.UltraTabPageControl3.None6Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl3.None6.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ4' with focus on 'FrmSglBooking.UltraTabPageControl3.None6'.", repo.FrmSglBooking.UltraTabPageControl3.None6Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl3.None6.PressKeys(champ4);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None7' at 40;9.", repo.FrmSglBooking.UltraTabPageControl3.None7Info, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl3.None7.Click("40;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ5' with focus on 'FrmSglBooking.UltraTabPageControl3.None7'.", repo.FrmSglBooking.UltraTabPageControl3.None7Info, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl3.None7.PressKeys(champ5);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None' at 50;8.", repo.FrmSglBooking.UltraTabPageControl3.NoneInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl3.None.Click("50;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ6' with focus on 'FrmSglBooking.UltraTabPageControl3.None'.", repo.FrmSglBooking.UltraTabPageControl3.NoneInfo, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl3.None.PressKeys(champ6);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None1' at 27;10.", repo.FrmSglBooking.UltraTabPageControl3.None1Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl3.None1.Click("27;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ7' with focus on 'FrmSglBooking.UltraTabPageControl3.None1'.", repo.FrmSglBooking.UltraTabPageControl3.None1Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl3.None1.PressKeys(champ7);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None2' at 34;9.", repo.FrmSglBooking.UltraTabPageControl3.None2Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl3.None2.Click("34;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ8' with focus on 'FrmSglBooking.UltraTabPageControl3.None2'.", repo.FrmSglBooking.UltraTabPageControl3.None2Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl3.None2.PressKeys(champ8);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None8' at 49;9.", repo.FrmSglBooking.UltraTabPageControl3.None8Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl3.None8.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ9' with focus on 'FrmSglBooking.UltraTabPageControl3.None8'.", repo.FrmSglBooking.UltraTabPageControl3.None8Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl3.None8.PressKeys(champ9);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl3.None9' at 73;9.", repo.FrmSglBooking.UltraTabPageControl3.None9Info, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl3.None9.Click("73;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$champ10' with focus on 'FrmSglBooking.UltraTabPageControl3.None9'.", repo.FrmSglBooking.UltraTabPageControl3.None9Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl3.None9.PressKeys(champ10);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
