///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createTarifs recording.
    /// </summary>
    [TestModule("c4733b1b-5ff9-4823-9f9e-795039cdcfc0", ModuleType.Recording, 1)]
    public partial class createTarifs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createTarifs instance = new createTarifs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createTarifs()
        {
            tauxOfficiel = "{NumPad1}";
            tauxAchat = "{NumPad1}";
            tauxVente = "{NumPad1}";
            tarifPublie = "{NumPad1}";
            tarifNegocie = "{NumPad1}";
            penalite = "{NumPad1}";
            codeTaxe = "153;6";
            taxe = "{NumPad1}";
            remiseAuClientPourcent = "{NumPad1}";
            remiseAuClient = "{NumPad1}";
            tarifMaximal = "{NumPad1}";
            tarifMinimal = "{NumPad1}";
            cash = "{NumPad1}";
            numeroCheque = "{NumPad1}";
            cheque = "{NumPad1}";
            nonRef = "{NumPad1}";
            numeroCC = "{NumPad1}";
            carteCredit = "{NumPad1}";
            code = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createTarifs Instance
        {
            get { return instance; }
        }

#region Variables

        string _tauxOfficiel;

        /// <summary>
        /// Gets or sets the value of variable tauxOfficiel.
        /// </summary>
        [TestVariable("ca72994c-1f52-498a-b5d5-5067c049b536")]
        public string tauxOfficiel
        {
            get { return _tauxOfficiel; }
            set { _tauxOfficiel = value; }
        }

        string _tauxAchat;

        /// <summary>
        /// Gets or sets the value of variable tauxAchat.
        /// </summary>
        [TestVariable("edc9e5eb-9e02-40ae-a984-0f73d1819ff4")]
        public string tauxAchat
        {
            get { return _tauxAchat; }
            set { _tauxAchat = value; }
        }

        string _tauxVente;

        /// <summary>
        /// Gets or sets the value of variable tauxVente.
        /// </summary>
        [TestVariable("a9016cb3-ee4e-41fb-be35-4eb0b34f0a9d")]
        public string tauxVente
        {
            get { return _tauxVente; }
            set { _tauxVente = value; }
        }

        string _tarifPublie;

        /// <summary>
        /// Gets or sets the value of variable tarifPublie.
        /// </summary>
        [TestVariable("e65e4d3a-cc8c-4fa4-baf0-4098db8054e7")]
        public string tarifPublie
        {
            get { return _tarifPublie; }
            set { _tarifPublie = value; }
        }

        string _tarifNegocie;

        /// <summary>
        /// Gets or sets the value of variable tarifNegocie.
        /// </summary>
        [TestVariable("376d3356-2eee-4b95-b53a-1a21dd483dfe")]
        public string tarifNegocie
        {
            get { return _tarifNegocie; }
            set { _tarifNegocie = value; }
        }

        string _penalite;

        /// <summary>
        /// Gets or sets the value of variable penalite.
        /// </summary>
        [TestVariable("a9c315c9-cc3e-4623-b908-04c0dd6b397c")]
        public string penalite
        {
            get { return _penalite; }
            set { _penalite = value; }
        }

        string _codeTaxe;

        /// <summary>
        /// Gets or sets the value of variable codeTaxe.
        /// </summary>
        [TestVariable("a30b6614-9741-4d88-a981-6dd6fee8537c")]
        public string codeTaxe
        {
            get { return _codeTaxe; }
            set { _codeTaxe = value; }
        }

        string _taxe;

        /// <summary>
        /// Gets or sets the value of variable taxe.
        /// </summary>
        [TestVariable("7082a4d1-578c-4aea-962d-9940c072b551")]
        public string taxe
        {
            get { return _taxe; }
            set { _taxe = value; }
        }

        string _remiseAuClientPourcent;

        /// <summary>
        /// Gets or sets the value of variable remiseAuClientPourcent.
        /// </summary>
        [TestVariable("ae6b4665-2a68-45d7-8fad-9b9410527507")]
        public string remiseAuClientPourcent
        {
            get { return _remiseAuClientPourcent; }
            set { _remiseAuClientPourcent = value; }
        }

        string _remiseAuClient;

        /// <summary>
        /// Gets or sets the value of variable remiseAuClient.
        /// </summary>
        [TestVariable("8cf32310-d69f-4d8e-8261-bec5b5de31a6")]
        public string remiseAuClient
        {
            get { return _remiseAuClient; }
            set { _remiseAuClient = value; }
        }

        string _tarifMaximal;

        /// <summary>
        /// Gets or sets the value of variable tarifMaximal.
        /// </summary>
        [TestVariable("48dac074-ce8c-47dd-877e-b20ef7aa4974")]
        public string tarifMaximal
        {
            get { return _tarifMaximal; }
            set { _tarifMaximal = value; }
        }

        string _tarifMinimal;

        /// <summary>
        /// Gets or sets the value of variable tarifMinimal.
        /// </summary>
        [TestVariable("354d7b5b-0ea5-4161-af44-058e245409fe")]
        public string tarifMinimal
        {
            get { return _tarifMinimal; }
            set { _tarifMinimal = value; }
        }

        string _cash;

        /// <summary>
        /// Gets or sets the value of variable cash.
        /// </summary>
        [TestVariable("ebc2319a-b122-411b-b7ed-71b855acc769")]
        public string cash
        {
            get { return _cash; }
            set { _cash = value; }
        }

        string _numeroCheque;

        /// <summary>
        /// Gets or sets the value of variable numeroCheque.
        /// </summary>
        [TestVariable("b9ee27b9-eab8-49f4-ba32-b60e6f3e710d")]
        public string numeroCheque
        {
            get { return _numeroCheque; }
            set { _numeroCheque = value; }
        }

        string _cheque;

        /// <summary>
        /// Gets or sets the value of variable cheque.
        /// </summary>
        [TestVariable("debc4ee0-411b-49aa-8bae-286555fba306")]
        public string cheque
        {
            get { return _cheque; }
            set { _cheque = value; }
        }

        string _nonRef;

        /// <summary>
        /// Gets or sets the value of variable nonRef.
        /// </summary>
        [TestVariable("1370650d-35b5-4a2c-b212-209761b3ce9f")]
        public string nonRef
        {
            get { return _nonRef; }
            set { _nonRef = value; }
        }

        string _numeroCC;

        /// <summary>
        /// Gets or sets the value of variable numeroCC.
        /// </summary>
        [TestVariable("7be5dd18-7aba-45c6-832e-0323a344a446")]
        public string numeroCC
        {
            get { return _numeroCC; }
            set { _numeroCC = value; }
        }

        string _carteCredit;

        /// <summary>
        /// Gets or sets the value of variable carteCredit.
        /// </summary>
        [TestVariable("c2c8da9a-6455-4dec-a81e-ea5f4d552c71")]
        public string carteCredit
        {
            get { return _carteCredit; }
            set { _carteCredit = value; }
        }

        string _code;

        /// <summary>
        /// Gets or sets the value of variable code.
        /// </summary>
        [TestVariable("79cfb239-c335-40d5-b0a1-b6a962cf5b94")]
        public string code
        {
            get { return _code; }
            set { _code = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable devise.
        /// </summary>
        [TestVariable("3799edea-fecf-4c87-8bb8-68f77bd66919")]
        public string devise
        {
            get { return repo.devise; }
            set { repo.devise = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable reasonCode.
        /// </summary>
        [TestVariable("54ef5a7c-c8b0-4873-a020-3ffeebfb858a")]
        public string reasonCode
        {
            get { return repo.reasonCode; }
            set { repo.reasonCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageTarifs' at 19;6.", repo.FrmSglBooking.TabPageTarifsInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageTarifs.Click("19;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.Open' at 6;7.", repo.FrmSglBooking.UltraTabPageControl2.OpenInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl2.Open.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItemMRO' at 33;9.", repo.Bora.ListItemMROInfo, new RecordItemIndex(2));
            repo.Bora.ListItemMRO.Click("33;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown' at 14;8.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDownInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown.Click("14;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None2' at 58;11.", repo.Bora.None2Info, new RecordItemIndex(4));
            repo.Bora.None2.Click("58;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxOfficiel' with focus on 'Bora.None2'.", repo.Bora.None2Info, new RecordItemIndex(5));
            repo.Bora.None2.PressKeys(tauxOfficiel);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None3' at 58;7.", repo.Bora.None3Info, new RecordItemIndex(6));
            repo.Bora.None3.Click("58;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxAchat' with focus on 'Bora.None3'.", repo.Bora.None3Info, new RecordItemIndex(7));
            repo.Bora.None3.PressKeys(tauxAchat);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None4' at 57;9.", repo.Bora.None4Info, new RecordItemIndex(8));
            repo.Bora.None4.Click("57;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxVente' with focus on 'Bora.None4'.", repo.Bora.None4Info, new RecordItemIndex(9));
            repo.Bora.None4.PressKeys(tauxVente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None5' at 51;9.", repo.Bora.None5Info, new RecordItemIndex(10));
            repo.Bora.None5.Click("51;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions' at 40;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.Click("40;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown1' at 13;8.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown1Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown1.Click("13;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None6' at 22;10.", repo.Bora.None6Info, new RecordItemIndex(14));
            repo.Bora.None6.Click("22;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifPublie' with focus on 'Bora.None6'.", repo.Bora.None6Info, new RecordItemIndex(15));
            repo.Bora.None6.PressKeys(tarifPublie);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None7' at 25;13.", repo.Bora.None7Info, new RecordItemIndex(16));
            repo.Bora.None7.Click("25;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifNegocie' with focus on 'Bora.None7'.", repo.Bora.None7Info, new RecordItemIndex(17));
            repo.Bora.None7.PressKeys(tarifNegocie);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None8' at 25;12.", repo.Bora.None8Info, new RecordItemIndex(18));
            repo.Bora.None8.Click("25;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$penalite' with focus on 'Bora.None8'.", repo.Bora.None8Info, new RecordItemIndex(19));
            repo.Bora.None8.PressKeys(penalite);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None9' at 34;11.", repo.Bora.None9Info, new RecordItemIndex(20));
            repo.Bora.None9.Click("34;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.BtnRefreshTotalTaxesBooking' at 9;11.", repo.Bora.BtnRefreshTotalTaxesBookingInfo, new RecordItemIndex(21));
            repo.Bora.BtnRefreshTotalTaxesBooking.Click("9;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None10' at 39;9.", repo.Bora.None10Info, new RecordItemIndex(22));
            repo.Bora.None10.Click("39;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$code' with focus on 'Bora.None10'.", repo.Bora.None10Info, new RecordItemIndex(23));
            repo.Bora.None10.PressKeys(code);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None11' at 107;10.", repo.Bora.None11Info, new RecordItemIndex(24));
            repo.Bora.None11.Click("107;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$taxe' with focus on 'Bora.None11'.", repo.Bora.None11Info, new RecordItemIndex(25));
            repo.Bora.None11.PressKeys(taxe);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'Bora.None11'.", repo.Bora.None11Info, new RecordItemIndex(26));
            repo.Bora.None11.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1' at 119;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(27));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1.Click("119;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.Open1' at 5;5.", repo.FrmSglBooking.UltraTabPageControl21.Open1Info, new RecordItemIndex(29));
            repo.FrmSglBooking.UltraTabPageControl21.Open1.Click("5;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $codeTaxe.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(30));
            repo.Bora.ScrollingRegion.Click(codeTaxe);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown2' at 10;8.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown2Info, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown2.Click("10;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None12' at 16;8.", repo.Bora.None12Info, new RecordItemIndex(32));
            repo.Bora.None12.Click("16;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None13' at 15;12.", repo.Bora.None13Info, new RecordItemIndex(33));
            repo.Bora.None13.Click("15;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None14' at 15;7.", repo.Bora.None14Info, new RecordItemIndex(34));
            repo.Bora.None14.Click("15;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None15' at 17;9.", repo.Bora.None15Info, new RecordItemIndex(35));
            repo.Bora.None15.Click("17;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None16' at 18;6.", repo.Bora.None16Info, new RecordItemIndex(36));
            repo.Bora.None16.Click("18;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2' at 67;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2Info, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2.Click("67;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None' at 95;10.", repo.FrmSglBooking.UltraTabPageControl2.NoneInfo, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl2.None.Click("95;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.None'.", repo.FrmSglBooking.UltraTabPageControl2.NoneInfo, new RecordItemIndex(39));
            repo.FrmSglBooking.UltraTabPageControl2.None.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown3' at 14;6.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown3Info, new RecordItemIndex(40));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown3.Click("14;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None17' at 29;11.", repo.Bora.None17Info, new RecordItemIndex(41));
            repo.Bora.None17.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None18' at 29;9.", repo.Bora.None18Info, new RecordItemIndex(42));
            repo.Bora.None18.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None19' at 29;11.", repo.Bora.None19Info, new RecordItemIndex(43));
            repo.Bora.None19.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None20' at 29;10.", repo.Bora.None20Info, new RecordItemIndex(44));
            repo.Bora.None20.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None21' at 31;8.", repo.Bora.None21Info, new RecordItemIndex(45));
            repo.Bora.None21.Click("31;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3' at 54;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3Info, new RecordItemIndex(46));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3.Click("54;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3Info, new RecordItemIndex(47));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None1' at 141;10.", repo.FrmSglBooking.UltraTabPageControl2.None1Info, new RecordItemIndex(48));
            repo.FrmSglBooking.UltraTabPageControl2.None1.Click("141;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.None1'.", repo.FrmSglBooking.UltraTabPageControl2.None1Info, new RecordItemIndex(49));
            repo.FrmSglBooking.UltraTabPageControl2.None1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None2' at 26;10.", repo.FrmSglBooking.UltraTabPageControl2.None2Info, new RecordItemIndex(50));
            repo.FrmSglBooking.UltraTabPageControl2.None2.Click("26;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$remiseAuClientPourcent' with focus on 'FrmSglBooking.UltraTabPageControl2.None2'.", repo.FrmSglBooking.UltraTabPageControl2.None2Info, new RecordItemIndex(51));
            repo.FrmSglBooking.UltraTabPageControl2.None2.PressKeys(remiseAuClientPourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None3' at 70;10.", repo.FrmSglBooking.UltraTabPageControl2.None3Info, new RecordItemIndex(52));
            repo.FrmSglBooking.UltraTabPageControl2.None3.Click("70;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$remiseAuClient' with focus on 'FrmSglBooking.UltraTabPageControl2.None3'.", repo.FrmSglBooking.UltraTabPageControl2.None3Info, new RecordItemIndex(53));
            repo.FrmSglBooking.UltraTabPageControl2.None3.PressKeys(remiseAuClient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.Text199' at 131;6.", repo.FrmSglBooking.UltraTabPageControl2.Text199Info, new RecordItemIndex(54));
            repo.FrmSglBooking.UltraTabPageControl2.Text199.Click("131;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None4' at 50;9.", repo.FrmSglBooking.UltraTabPageControl21.None4Info, new RecordItemIndex(55));
            repo.FrmSglBooking.UltraTabPageControl21.None4.Click("50;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifMaximal' with focus on 'FrmSglBooking.UltraTabPageControl21.None4'.", repo.FrmSglBooking.UltraTabPageControl21.None4Info, new RecordItemIndex(56));
            repo.FrmSglBooking.UltraTabPageControl21.None4.PressKeys(tarifMaximal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None5' at 74;10.", repo.FrmSglBooking.UltraTabPageControl21.None5Info, new RecordItemIndex(57));
            repo.FrmSglBooking.UltraTabPageControl21.None5.Click("74;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifMinimal' with focus on 'FrmSglBooking.UltraTabPageControl21.None5'.", repo.FrmSglBooking.UltraTabPageControl21.None5Info, new RecordItemIndex(58));
            repo.FrmSglBooking.UltraTabPageControl21.None5.PressKeys(tarifMinimal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.Open2' at 6;7.", repo.FrmSglBooking.UltraTabPageControl21.Open2Info, new RecordItemIndex(59));
            repo.FrmSglBooking.UltraTabPageControl21.Open2.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItem' at 89;6.", repo.Bora.ListItemInfo, new RecordItemIndex(60));
            repo.Bora.ListItem.Click("89;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None6' at 74;10.", repo.FrmSglBooking.UltraTabPageControl21.None6Info, new RecordItemIndex(61));
            repo.FrmSglBooking.UltraTabPageControl21.None6.Click("74;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cash' with focus on 'FrmSglBooking.UltraTabPageControl21.None6'.", repo.FrmSglBooking.UltraTabPageControl21.None6Info, new RecordItemIndex(62));
            repo.FrmSglBooking.UltraTabPageControl21.None6.PressKeys(cash);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.ButtonDropDown4' at 11;6.", repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4Info, new RecordItemIndex(63));
            repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4.Click("11;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None22' at 19;10.", repo.Bora.None22Info, new RecordItemIndex(64));
            repo.Bora.None22.Click("19;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroCheque' with focus on 'Bora.None22'.", repo.Bora.None22Info, new RecordItemIndex(65));
            repo.Bora.None22.PressKeys(numeroCheque);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4' at 67;7.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(66));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.Click("67;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.ButtonDropDown4' at 16;10.", repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4Info, new RecordItemIndex(67));
            repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None22' at 16;10.", repo.Bora.None22Info, new RecordItemIndex(68));
            repo.Bora.None22.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'Bora.None22'.", repo.Bora.None22Info, new RecordItemIndex(69));
            repo.Bora.None22.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4' at 96;8.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(70));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.Click("96;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cheque' with focus on 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4'.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(71));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.PressKeys(cheque);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None7' at 122;10.", repo.FrmSglBooking.UltraTabPageControl21.None7Info, new RecordItemIndex(72));
            repo.FrmSglBooking.UltraTabPageControl21.None7.Click("122;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$nonRef' with focus on 'FrmSglBooking.UltraTabPageControl21.None7'.", repo.FrmSglBooking.UltraTabPageControl21.None7Info, new RecordItemIndex(73));
            repo.FrmSglBooking.UltraTabPageControl21.None7.PressKeys(nonRef);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.ButtonDropDown5' at 13;9.", repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown5Info, new RecordItemIndex(74));
            repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown5.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None23' at 15;8.", repo.Bora.None23Info, new RecordItemIndex(75));
            repo.Bora.None23.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroCC' with focus on 'Bora.None23'.", repo.Bora.None23Info, new RecordItemIndex(76));
            repo.Bora.None23.PressKeys(numeroCC);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4' at 90;5.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(77));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.Click("90;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$carteCredit' with focus on 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4'.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(78));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.PressKeys(carteCredit);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
