///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createNDC2 recording.
    /// </summary>
    [TestModule("e2dded0c-7521-4caf-888a-ca68f72fbb39", ModuleType.Recording, 1)]
    public partial class createNDC2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createNDC2 instance = new createNDC2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createNDC2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createNDC2 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ndcContent.
        /// </summary>
        [TestVariable("f45e6ecd-71b2-4002-8c0f-fd78ffaf3942")]
        public string ndcContent
        {
            get { return repo.ndcContent; }
            set { repo.ndcContent = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable reportingIndicator.
        /// </summary>
        [TestVariable("0c25bdbf-598a-445b-abb7-73df6e7e94e4")]
        public string reportingIndicator
        {
            get { return repo.reportingIndicator; }
            set { repo.reportingIndicator = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageNDC' at 26;8.", repo.FrmSglBooking.TabPageNDCInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageNDC.Click("26;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.ChkNdccontent' at 7;9.", repo.FrmSglBooking.ChkNdccontentInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.ChkNdccontent.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.Open' at 6;7.", repo.FrmSglBooking.OpenInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.Open.Click("6;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.BSPReported' at 80;8.", repo.Bora.BSPReportedInfo, new RecordItemIndex(3));
            repo.Bora.BSPReported.Click("80;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
