///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createMarge recording.
    /// </summary>
    [TestModule("3b9b6097-0744-4aad-bbc1-27d60944ca17", ModuleType.Recording, 1)]
    public partial class createMarge : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createMarge instance = new createMarge();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createMarge()
        {
            commissionPourcent = "{NumPad1}";
            commission = "{NumPad2}";
            commissionSurPenalite = "{NumPad1}";
            bookingAgent = "126;9";
            ticketingAgent = "86;8";
            demarcheur = "139;9";
            comAgvPartenairePourcent = "{NumPad1}";
            comAgvPartenaire = "{NumPad2}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createMarge Instance
        {
            get { return instance; }
        }

#region Variables

        string _commissionPourcent;

        /// <summary>
        /// Gets or sets the value of variable commissionPourcent.
        /// </summary>
        [TestVariable("431293cb-d644-4821-95bf-3d04bd53f8da")]
        public string commissionPourcent
        {
            get { return _commissionPourcent; }
            set { _commissionPourcent = value; }
        }

        string _commission;

        /// <summary>
        /// Gets or sets the value of variable commission.
        /// </summary>
        [TestVariable("430b0f8f-c179-47b8-9c6c-38fae3a0b83b")]
        public string commission
        {
            get { return _commission; }
            set { _commission = value; }
        }

        string _commissionSurPenalite;

        /// <summary>
        /// Gets or sets the value of variable commissionSurPenalite.
        /// </summary>
        [TestVariable("3f7f8305-a20f-4739-a5d4-319efa133a5a")]
        public string commissionSurPenalite
        {
            get { return _commissionSurPenalite; }
            set { _commissionSurPenalite = value; }
        }

        string _bookingAgent;

        /// <summary>
        /// Gets or sets the value of variable bookingAgent.
        /// </summary>
        [TestVariable("c9ff868f-d040-4fb7-8677-90d9d20b6e09")]
        public string bookingAgent
        {
            get { return _bookingAgent; }
            set { _bookingAgent = value; }
        }

        string _ticketingAgent;

        /// <summary>
        /// Gets or sets the value of variable ticketingAgent.
        /// </summary>
        [TestVariable("f815ab04-2d3c-47ab-9527-06c4d5e75ba6")]
        public string ticketingAgent
        {
            get { return _ticketingAgent; }
            set { _ticketingAgent = value; }
        }

        string _demarcheur;

        /// <summary>
        /// Gets or sets the value of variable demarcheur.
        /// </summary>
        [TestVariable("2143e7a0-e09d-45e5-82cc-8e5e72aafaad")]
        public string demarcheur
        {
            get { return _demarcheur; }
            set { _demarcheur = value; }
        }

        string _comAgvPartenairePourcent;

        /// <summary>
        /// Gets or sets the value of variable comAgvPartenairePourcent.
        /// </summary>
        [TestVariable("e027943c-0fa6-4c9d-91f1-8ec2e9b0023e")]
        public string comAgvPartenairePourcent
        {
            get { return _comAgvPartenairePourcent; }
            set { _comAgvPartenairePourcent = value; }
        }

        string _comAgvPartenaire;

        /// <summary>
        /// Gets or sets the value of variable comAgvPartenaire.
        /// </summary>
        [TestVariable("e5a01af0-a8ee-4cc4-849d-479d33c83e77")]
        public string comAgvPartenaire
        {
            get { return _comAgvPartenaire; }
            set { _comAgvPartenaire = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageMarge' at 30;11.", repo.FrmSglBooking.TabPageMargeInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageMarge.Click("30;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None' at 29;9.", repo.FrmSglBooking.UltraTabPageControl5.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl5.None.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commissionPourcent' with focus on 'FrmSglBooking.UltraTabPageControl5.None'.", repo.FrmSglBooking.UltraTabPageControl5.NoneInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl5.None.PressKeys(commissionPourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None1' at 58;8.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl5.None1.Click("58;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl5.None1'.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl5.None1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None2' at 143;11.", repo.FrmSglBooking.UltraTabPageControl5.None2Info, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl5.None2.Click("143;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None1' at 63;12.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl5.None1.Click("63;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'FrmSglBooking.UltraTabPageControl5.None1'.", repo.FrmSglBooking.UltraTabPageControl5.None1Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl5.None1.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions' at 71;10.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions.Click("71;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions' at 75;9.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions.Click("75;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commission' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions.PressKeys(commission);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None2' at 137;11.", repo.FrmSglBooking.UltraTabPageControl5.None2Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl5.None2.Click("137;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$commissionSurPenalite' with focus on 'FrmSglBooking.UltraTabPageControl5.None2'.", repo.FrmSglBooking.UltraTabPageControl5.None2Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl5.None2.PressKeys(commissionSurPenalite);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None3' at 131;11.", repo.FrmSglBooking.UltraTabPageControl5.None3Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl5.None3.Click("131;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}' with focus on 'FrmSglBooking.UltraTabPageControl5.None3'.", repo.FrmSglBooking.UltraTabPageControl5.None3Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl5.None3.PressKeys("{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'FrmSglBooking.UltraTabPageControl5.None3'.", repo.FrmSglBooking.UltraTabPageControl5.None3Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl5.None3.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None4' at 111;13.", repo.FrmSglBooking.UltraTabPageControl5.None4Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl5.None4.Click("111;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.ButtonDropDown' at 14;10.", repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDownInfo, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None24' at 31;10.", repo.Bora.None24Info, new RecordItemIndex(20));
            repo.Bora.None24.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None25' at 27;14.", repo.Bora.None25Info, new RecordItemIndex(21));
            repo.Bora.None25.Click("27;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None26' at 28;10.", repo.Bora.None26Info, new RecordItemIndex(22));
            repo.Bora.None26.Click("28;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None27' at 29;11.", repo.Bora.None27Info, new RecordItemIndex(23));
            repo.Bora.None27.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None28' at 30;8.", repo.Bora.None28Info, new RecordItemIndex(24));
            repo.Bora.None28.Click("30;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1' at 18;7.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.Click("18;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(26));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(27));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FrmSglBooking.UltraTabPageControl5.None5' at 65;11.", repo.FrmSglBooking.UltraTabPageControl5.None5Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl5.None5.MoveTo("65;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'FrmSglBooking.UltraTabPageControl5.None5' at 53;38.", repo.FrmSglBooking.UltraTabPageControl5.None5Info, new RecordItemIndex(29));
            repo.FrmSglBooking.UltraTabPageControl5.None5.MoveTo("53;38");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FrmSglBooking.UltraTabPageControl5.None5' at 93;11.", repo.FrmSglBooking.UltraTabPageControl5.None5Info, new RecordItemIndex(30));
            repo.FrmSglBooking.UltraTabPageControl5.None5.MoveTo("93;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None6' at 115;6.", repo.FrmSglBooking.UltraTabPageControl5.None6Info, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl5.None6.Click("115;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Text279' at 111;8.", repo.FrmSglBooking.UltraTabPageControl5.Text279Info, new RecordItemIndex(32));
            repo.FrmSglBooking.UltraTabPageControl5.Text279.Click("111;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Text279' at 111;8.", repo.FrmSglBooking.UltraTabPageControl5.Text279Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl5.Text279.Click("111;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open' at 6;6.", repo.FrmSglBooking.UltraTabPageControl5.OpenInfo, new RecordItemIndex(34));
            repo.FrmSglBooking.UltraTabPageControl5.Open.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $bookingAgent.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(35));
            repo.Bora.ScrollingRegion.Click(bookingAgent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None7' at 21;9.", repo.FrmSglBooking.UltraTabPageControl5.None7Info, new RecordItemIndex(36));
            repo.FrmSglBooking.UltraTabPageControl5.None7.Click("21;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None8' at 48;9.", repo.FrmSglBooking.UltraTabPageControl5.None8Info, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl5.None8.Click("48;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open1' at 9;7.", repo.FrmSglBooking.UltraTabPageControl5.Open1Info, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl5.Open1.Click("9;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $ticketingAgent.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(39));
            repo.Bora.ScrollingRegion.Click(ticketingAgent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None9' at 20;9.", repo.FrmSglBooking.UltraTabPageControl5.None9Info, new RecordItemIndex(40));
            repo.FrmSglBooking.UltraTabPageControl5.None9.Click("20;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None10' at 46;6.", repo.FrmSglBooking.UltraTabPageControl5.None10Info, new RecordItemIndex(41));
            repo.FrmSglBooking.UltraTabPageControl5.None10.Click("46;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Open2' at 5;7.", repo.FrmSglBooking.UltraTabPageControl5.Open2Info, new RecordItemIndex(42));
            repo.FrmSglBooking.UltraTabPageControl5.Open2.Click("5;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $demarcheur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(43));
            repo.Bora.ScrollingRegion.Click(demarcheur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None11' at 23;10.", repo.FrmSglBooking.UltraTabPageControl5.None11Info, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl5.None11.Click("23;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None12' at 13;9.", repo.FrmSglBooking.UltraTabPageControl5.None12Info, new RecordItemIndex(45));
            repo.FrmSglBooking.UltraTabPageControl5.None12.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.ButtonDropDown1' at 12;10.", repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown1Info, new RecordItemIndex(46));
            repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown1.Click("12;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None29' at 103;12.", repo.Bora.None29Info, new RecordItemIndex(47));
            repo.Bora.None29.Click("103;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None30' at 22;13.", repo.Bora.None30Info, new RecordItemIndex(48));
            repo.Bora.None30.Click("22;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$comAgvPartenairePourcent' with focus on 'Bora.None30'.", repo.Bora.None30Info, new RecordItemIndex(49));
            repo.Bora.None30.PressKeys(comAgvPartenairePourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None31' at 71;11.", repo.Bora.None31Info, new RecordItemIndex(50));
            repo.Bora.None31.Click("71;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'Bora.None31'.", repo.Bora.None31Info, new RecordItemIndex(51));
            repo.Bora.None31.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$comAgvPartenaire' with focus on 'Bora.None31'.", repo.Bora.None31Info, new RecordItemIndex(52));
            repo.Bora.None31.PressKeys(comAgvPartenaire);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1' at 104;8.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(53));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.Click("104;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.None13' at 133;12.", repo.FrmSglBooking.UltraTabPageControl5.None13Info, new RecordItemIndex(54));
            repo.FrmSglBooking.UltraTabPageControl5.None13.Click("133;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.Text1301' at 120;8.", repo.FrmSglBooking.UltraTabPageControl5.Text1301Info, new RecordItemIndex(55));
            repo.FrmSglBooking.UltraTabPageControl5.Text1301.Click("120;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
