///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createTarifs3 recording.
    /// </summary>
    [TestModule("fb21daa7-d745-476b-bfe5-d204229440c7", ModuleType.Recording, 1)]
    public partial class createTarifs3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createTarifs3 instance = new createTarifs3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createTarifs3()
        {
            tauxOfficiel = "{NumPad1}";
            tauxAchat = "{NumPad1}";
            tauxVente = "{NumPad1}";
            tarifPublie = "{NumPad1}";
            tarifNegocie = "{NumPad1}";
            penalite = "{NumPad1}";
            code = "{NumPad1}";
            taxe = "{NumPad1}";
            codeTaxe = "158;11";
            remiseAuClientPourcent = "{NumPad1}";
            remiseAuClient = "{NumPad1}";
            tarifMaximal = "{NumPad1}";
            tarifMinimal = "{NumPad1}";
            cash = "{NumPad1}";
            numeroCheque = "{NumPad1}";
            cheque = "{NumPad1}";
            nonRef = "{NumPad1}";
            numeroCC = "{NumPad1}";
            carteDeCredit = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createTarifs3 Instance
        {
            get { return instance; }
        }

#region Variables

        string _tauxOfficiel;

        /// <summary>
        /// Gets or sets the value of variable tauxOfficiel.
        /// </summary>
        [TestVariable("cf70c30f-07d6-4358-a4c5-78490fcfc5ec")]
        public string tauxOfficiel
        {
            get { return _tauxOfficiel; }
            set { _tauxOfficiel = value; }
        }

        string _tauxAchat;

        /// <summary>
        /// Gets or sets the value of variable tauxAchat.
        /// </summary>
        [TestVariable("3c33c2d8-11d2-48fc-909b-5ed5974045ce")]
        public string tauxAchat
        {
            get { return _tauxAchat; }
            set { _tauxAchat = value; }
        }

        string _tauxVente;

        /// <summary>
        /// Gets or sets the value of variable tauxVente.
        /// </summary>
        [TestVariable("dea4fec1-8910-4c1d-a9f1-398c89968e4d")]
        public string tauxVente
        {
            get { return _tauxVente; }
            set { _tauxVente = value; }
        }

        string _tarifPublie;

        /// <summary>
        /// Gets or sets the value of variable tarifPublie.
        /// </summary>
        [TestVariable("2b7c466c-d559-478a-bb18-d468b76e8d9f")]
        public string tarifPublie
        {
            get { return _tarifPublie; }
            set { _tarifPublie = value; }
        }

        string _tarifNegocie;

        /// <summary>
        /// Gets or sets the value of variable tarifNegocie.
        /// </summary>
        [TestVariable("6292aaee-81b5-49fe-a921-2cee8c5e86cc")]
        public string tarifNegocie
        {
            get { return _tarifNegocie; }
            set { _tarifNegocie = value; }
        }

        string _penalite;

        /// <summary>
        /// Gets or sets the value of variable penalite.
        /// </summary>
        [TestVariable("f0171a03-a191-4db2-b41e-10d0a631ffa4")]
        public string penalite
        {
            get { return _penalite; }
            set { _penalite = value; }
        }

        string _code;

        /// <summary>
        /// Gets or sets the value of variable code.
        /// </summary>
        [TestVariable("e969ad61-4b21-43b7-8d29-0b16b0bffdce")]
        public string code
        {
            get { return _code; }
            set { _code = value; }
        }

        string _taxe;

        /// <summary>
        /// Gets or sets the value of variable taxe.
        /// </summary>
        [TestVariable("0f7f7bee-b240-48b9-a4a7-8f798c0c43ce")]
        public string taxe
        {
            get { return _taxe; }
            set { _taxe = value; }
        }

        string _codeTaxe;

        /// <summary>
        /// Gets or sets the value of variable codeTaxe.
        /// </summary>
        [TestVariable("4cef70e6-f2ff-4fae-852a-3c9f3f39711a")]
        public string codeTaxe
        {
            get { return _codeTaxe; }
            set { _codeTaxe = value; }
        }

        string _remiseAuClientPourcent;

        /// <summary>
        /// Gets or sets the value of variable remiseAuClientPourcent.
        /// </summary>
        [TestVariable("de0bb4e5-fe4b-4090-a1e9-f38b612c0b3c")]
        public string remiseAuClientPourcent
        {
            get { return _remiseAuClientPourcent; }
            set { _remiseAuClientPourcent = value; }
        }

        string _remiseAuClient;

        /// <summary>
        /// Gets or sets the value of variable remiseAuClient.
        /// </summary>
        [TestVariable("1ae29cae-da26-4d26-97da-6808c7f0031b")]
        public string remiseAuClient
        {
            get { return _remiseAuClient; }
            set { _remiseAuClient = value; }
        }

        string _tarifMaximal;

        /// <summary>
        /// Gets or sets the value of variable tarifMaximal.
        /// </summary>
        [TestVariable("17ac34af-4d82-41df-abe4-e2176d178fa5")]
        public string tarifMaximal
        {
            get { return _tarifMaximal; }
            set { _tarifMaximal = value; }
        }

        string _tarifMinimal;

        /// <summary>
        /// Gets or sets the value of variable tarifMinimal.
        /// </summary>
        [TestVariable("7ffc1ec4-75a5-4d63-806d-66c2dcf9931a")]
        public string tarifMinimal
        {
            get { return _tarifMinimal; }
            set { _tarifMinimal = value; }
        }

        string _cash;

        /// <summary>
        /// Gets or sets the value of variable cash.
        /// </summary>
        [TestVariable("0ee3b10e-43ba-4fe6-8ec6-c7f4b1045e2f")]
        public string cash
        {
            get { return _cash; }
            set { _cash = value; }
        }

        string _numeroCheque;

        /// <summary>
        /// Gets or sets the value of variable numeroCheque.
        /// </summary>
        [TestVariable("fdfb6a23-a4b6-47ff-b049-e62f3be3ccff")]
        public string numeroCheque
        {
            get { return _numeroCheque; }
            set { _numeroCheque = value; }
        }

        string _cheque;

        /// <summary>
        /// Gets or sets the value of variable cheque.
        /// </summary>
        [TestVariable("c4b44124-bf9f-4350-b1fa-30e152b03980")]
        public string cheque
        {
            get { return _cheque; }
            set { _cheque = value; }
        }

        string _nonRef;

        /// <summary>
        /// Gets or sets the value of variable nonRef.
        /// </summary>
        [TestVariable("da04c165-2068-4fce-88f5-502b9bef3245")]
        public string nonRef
        {
            get { return _nonRef; }
            set { _nonRef = value; }
        }

        string _numeroCC;

        /// <summary>
        /// Gets or sets the value of variable numeroCC.
        /// </summary>
        [TestVariable("079cb611-089a-4ae8-8ca8-87bc6d6575ed")]
        public string numeroCC
        {
            get { return _numeroCC; }
            set { _numeroCC = value; }
        }

        string _carteDeCredit;

        /// <summary>
        /// Gets or sets the value of variable carteDeCredit.
        /// </summary>
        [TestVariable("c84edf7a-c0c4-40a7-b235-07465434d4a2")]
        public string carteDeCredit
        {
            get { return _carteDeCredit; }
            set { _carteDeCredit = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable devise.
        /// </summary>
        [TestVariable("3799edea-fecf-4c87-8bb8-68f77bd66919")]
        public string devise
        {
            get { return repo.devise; }
            set { repo.devise = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageTarifs' at 25;10.", repo.FrmSglBooking.TabPageTarifsInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageTarifs.Click("25;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.Open' at 4;9.", repo.FrmSglBooking.UltraTabPageControl2.OpenInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl2.Open.Click("4;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItemMRO' at 24;8.", repo.Bora.ListItemMROInfo, new RecordItemIndex(2));
            repo.Bora.ListItemMRO.Click("24;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown' at 16;7.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDownInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown.Click("16;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None2' at 57;9.", repo.Bora.None2Info, new RecordItemIndex(4));
            repo.Bora.None2.Click("57;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxOfficiel' with focus on 'Bora.None2'.", repo.Bora.None2Info, new RecordItemIndex(5));
            repo.Bora.None2.PressKeys(tauxOfficiel);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None3' at 56;9.", repo.Bora.None3Info, new RecordItemIndex(6));
            repo.Bora.None3.Click("56;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxAchat' with focus on 'Bora.None3'.", repo.Bora.None3Info, new RecordItemIndex(7));
            repo.Bora.None3.PressKeys(tauxAchat);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None4' at 56;9.", repo.Bora.None4Info, new RecordItemIndex(8));
            repo.Bora.None4.Click("56;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tauxVente' with focus on 'Bora.None4'.", repo.Bora.None4Info, new RecordItemIndex(9));
            repo.Bora.None4.PressKeys(tauxVente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions' at 38;6.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.Click("38;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown1' at 15;7.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown1Info, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown1.Click("15;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None6' at 19;10.", repo.Bora.None6Info, new RecordItemIndex(13));
            repo.Bora.None6.Click("19;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifPublie' with focus on 'Bora.None6'.", repo.Bora.None6Info, new RecordItemIndex(14));
            repo.Bora.None6.PressKeys(tarifPublie);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None7' at 32;11.", repo.Bora.None7Info, new RecordItemIndex(15));
            repo.Bora.None7.Click("32;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifNegocie' with focus on 'Bora.None7'.", repo.Bora.None7Info, new RecordItemIndex(16));
            repo.Bora.None7.PressKeys(tarifNegocie);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None8' at 34;10.", repo.Bora.None8Info, new RecordItemIndex(17));
            repo.Bora.None8.Click("34;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$penalite' with focus on 'Bora.None8'.", repo.Bora.None8Info, new RecordItemIndex(18));
            repo.Bora.None8.PressKeys(penalite);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None10' at 43;9.", repo.Bora.None10Info, new RecordItemIndex(19));
            repo.Bora.None10.Click("43;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$code' with focus on 'Bora.None10'.", repo.Bora.None10Info, new RecordItemIndex(20));
            repo.Bora.None10.PressKeys(code);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None11' at 110;10.", repo.Bora.None11Info, new RecordItemIndex(21));
            repo.Bora.None11.Click("110;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$taxe' with focus on 'Bora.None11'.", repo.Bora.None11Info, new RecordItemIndex(22));
            repo.Bora.None11.PressKeys(taxe);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'Bora.None11'.", repo.Bora.None11Info, new RecordItemIndex(23));
            repo.Bora.None11.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1' at 118;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1.Click("118;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.Open1' at 8;9.", repo.FrmSglBooking.UltraTabPageControl21.Open1Info, new RecordItemIndex(26));
            repo.FrmSglBooking.UltraTabPageControl21.Open1.Click("8;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $codeTaxe.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(27));
            repo.Bora.ScrollingRegion.Click(codeTaxe);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None2' at 23;8.", repo.FrmSglBooking.UltraTabPageControl2.None2Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl2.None2.Click("23;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$remiseAuClientPourcent' with focus on 'FrmSglBooking.UltraTabPageControl2.None2'.", repo.FrmSglBooking.UltraTabPageControl2.None2Info, new RecordItemIndex(29));
            repo.FrmSglBooking.UltraTabPageControl2.None2.PressKeys(remiseAuClientPourcent);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None3' at 73;10.", repo.FrmSglBooking.UltraTabPageControl2.None3Info, new RecordItemIndex(30));
            repo.FrmSglBooking.UltraTabPageControl2.None3.Click("73;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$remiseAuClient' with focus on 'FrmSglBooking.UltraTabPageControl2.None3'.", repo.FrmSglBooking.UltraTabPageControl2.None3Info, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl2.None3.PressKeys(remiseAuClient);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None4' at 139;9.", repo.FrmSglBooking.UltraTabPageControl21.None4Info, new RecordItemIndex(32));
            repo.FrmSglBooking.UltraTabPageControl21.None4.Click("139;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifMaximal' with focus on 'FrmSglBooking.UltraTabPageControl21.None4'.", repo.FrmSglBooking.UltraTabPageControl21.None4Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl21.None4.PressKeys(tarifMaximal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None5' at 143;9.", repo.FrmSglBooking.UltraTabPageControl21.None5Info, new RecordItemIndex(34));
            repo.FrmSglBooking.UltraTabPageControl21.None5.Click("143;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$tarifMinimal' with focus on 'FrmSglBooking.UltraTabPageControl21.None5'.", repo.FrmSglBooking.UltraTabPageControl21.None5Info, new RecordItemIndex(35));
            repo.FrmSglBooking.UltraTabPageControl21.None5.PressKeys(tarifMinimal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None6' at 111;10.", repo.FrmSglBooking.UltraTabPageControl21.None6Info, new RecordItemIndex(36));
            repo.FrmSglBooking.UltraTabPageControl21.None6.Click("111;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cash' with focus on 'FrmSglBooking.UltraTabPageControl21.None6'.", repo.FrmSglBooking.UltraTabPageControl21.None6Info, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl21.None6.PressKeys(cash);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.ButtonDropDown4' at 17;7.", repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4Info, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown4.Click("17;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None22' at 19;11.", repo.Bora.None22Info, new RecordItemIndex(39));
            repo.Bora.None22.Click("19;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroCheque' with focus on 'Bora.None22'.", repo.Bora.None22Info, new RecordItemIndex(40));
            repo.Bora.None22.PressKeys(numeroCheque);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4' at 27;6.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(41));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.Click("27;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cheque' with focus on 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4'.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(42));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.PressKeys(cheque);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.None7' at 63;9.", repo.FrmSglBooking.UltraTabPageControl21.None7Info, new RecordItemIndex(43));
            repo.FrmSglBooking.UltraTabPageControl21.None7.Click("63;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$nonRef' with focus on 'FrmSglBooking.UltraTabPageControl21.None7'.", repo.FrmSglBooking.UltraTabPageControl21.None7Info, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl21.None7.PressKeys(nonRef);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.ButtonDropDown5' at 13;9.", repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown5Info, new RecordItemIndex(45));
            repo.FrmSglBooking.UltraTabPageControl21.ButtonDropDown5.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.None23' at 10;10.", repo.Bora.None23Info, new RecordItemIndex(46));
            repo.Bora.None23.Click("10;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroCC' with focus on 'Bora.None23'.", repo.Bora.None23Info, new RecordItemIndex(47));
            repo.Bora.None23.PressKeys(numeroCC);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4' at 101;8.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(48));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.Click("101;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$carteDeCredit' with focus on 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4'.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4Info, new RecordItemIndex(49));
            repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions4.PressKeys(carteDeCredit);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
