///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createNDC recording.
    /// </summary>
    [TestModule("f6fd4365-23d5-4a3e-a433-5dd1ea4ed37f", ModuleType.Recording, 1)]
    public partial class createNDC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createNDC instance = new createNDC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createNDC()
        {
            nomClient2 = "166;26";
            nomVoyageur = "133;7";
            ticketingAgent2 = "119;25";
            cash2 = "{NumPad3},{NumPad7}{NumPad8}";
            id = "UC-EV001";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createNDC Instance
        {
            get { return instance; }
        }

#region Variables

        string _nomClient2;

        /// <summary>
        /// Gets or sets the value of variable nomClient2.
        /// </summary>
        [TestVariable("db27ca6a-e744-4599-9893-53090e733228")]
        public string nomClient2
        {
            get { return _nomClient2; }
            set { _nomClient2 = value; }
        }

        string _nomVoyageur;

        /// <summary>
        /// Gets or sets the value of variable nomVoyageur.
        /// </summary>
        [TestVariable("907b6996-ccf7-41d2-a22d-ddb68c6d1ca6")]
        public string nomVoyageur
        {
            get { return _nomVoyageur; }
            set { _nomVoyageur = value; }
        }

        string _ticketingAgent2;

        /// <summary>
        /// Gets or sets the value of variable ticketingAgent2.
        /// </summary>
        [TestVariable("de4ab8e0-fd76-44e4-9e87-a8c95f6918c4")]
        public string ticketingAgent2
        {
            get { return _ticketingAgent2; }
            set { _ticketingAgent2 = value; }
        }

        string _cash2;

        /// <summary>
        /// Gets or sets the value of variable cash2.
        /// </summary>
        [TestVariable("37d46f6a-38f7-40c9-9a9c-414184b96022")]
        public string cash2
        {
            get { return _cash2; }
            set { _cash2 = value; }
        }

        string _id;

        /// <summary>
        /// Gets or sets the value of variable id.
        /// </summary>
        [TestVariable("7be93d65-9433-4f20-9d93-902a1f170006")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ndcContent.
        /// </summary>
        [TestVariable("f45e6ecd-71b2-4002-8c0f-fd78ffaf3942")]
        public string ndcContent
        {
            get { return repo.ndcContent; }
            set { repo.ndcContent = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable reportingIndicator.
        /// </summary>
        [TestVariable("0c25bdbf-598a-445b-abb7-73df6e7e94e4")]
        public string reportingIndicator
        {
            get { return repo.reportingIndicator; }
            set { repo.reportingIndicator = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable typeDocument2.
        /// </summary>
        [TestVariable("1164f69a-9d74-4f4b-8864-0f6c2fc34b96")]
        public string typeDocument2
        {
            get { return repo.typeDocument2; }
            set { repo.typeDocument2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp' at 23;11.", repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXpInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp.Click("23;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageNDC' at 31;7.", repo.FrmSglBooking.TabPageNDCInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.TabPageNDC.Click("31;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.ChkNdccontent' at 5;13.", repo.FrmSglBooking.ChkNdccontentInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.ChkNdccontent.Click("5;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.Open' at 6;9.", repo.FrmSglBooking.OpenInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.Open.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.BSPReported' at 98;7.", repo.Bora.BSPReportedInfo, new RecordItemIndex(4));
            repo.Bora.BSPReported.Click("98;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 16;10.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(5));
            repo.FrmSglBooking.BtnOk.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 43;10.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(6));
            repo.BoraMessageBox.ButtonOk.Click("43;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp' at 23;11.", repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXpInfo, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp.Click("23;11");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(8));
            //repo.FrmSglBooking.Self.EnsureVisible();
            //Keyboard.Press("");
            //Delay.Milliseconds(20);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(9));
            //repo.FrmSglBooking.Self.EnsureVisible();
            //Keyboard.Press(" ");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.CellATB' at 20;6.", repo.Bora.CellATBInfo, new RecordItemIndex(10));
            repo.Bora.CellATB.Click("20;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 42;13.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.BtnOk.Click("42;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 39;7.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(12));
            repo.BoraMessageBox.ButtonOk.Click("39;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 28;12.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(13));
            repo.FrmSglBooking.BtnOk.Click("28;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 44;11.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(14));
            repo.BoraMessageBox.ButtonOk.Click("44;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown1' at 6;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open8' at 6;8.", repo.FrmSglBooking.UltraTabPageControl1.Open8Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl1.Open8.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 6;6.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 6;6.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomClient2.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(19));
            repo.Bora.ScrollingRegion.Click(nomClient2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open8' at 8;8.", repo.FrmSglBooking.UltraTabPageControl1.Open8Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl1.Open8.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomVoyageur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(21));
            repo.Bora.ScrollingRegion.Click(nomVoyageur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 31;10.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(22));
            repo.FrmSglBooking.BtnOk.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 37;7.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(23));
            repo.BoraMessageBox.ButtonOk.Click("37;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $ticketingAgent2.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(24));
            repo.Bora.ScrollingRegion.Click(ticketingAgent2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 44;12.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(25));
            repo.FrmSglBooking.BtnOk.Click("44;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 34;9.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(26));
            repo.BoraMessageBox.ButtonOk.Click("34;9");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions' at 149;6.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(27));
            //repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions.MoveTo("149;6");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions' at 154;13.", repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(28));
            //repo.FrmSglBooking.UltraTabPageControl21.EmbeddableTextBoxWithUIPermissions.MoveTo("154;13");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cash2' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(29));
            repo.FrmSglBooking.Self.PressKeys(cash2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 48;8.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(30));
            repo.FrmSglBooking.BtnOk.Click("48;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'BoraMessageBox.LblText'.", repo.BoraMessageBox.LblTextInfo, new RecordItemIndex(31));
            //Validate.Exists(repo.BoraMessageBox.LblTextInfo);
            //Delay.Milliseconds(100);
            
            Validate_BilletK51EnregistreAvecSucces(repo.BoraMessageBox.BilletK51EnregistreAvecSuccesInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 31;10.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(33));
            repo.BoraMessageBox.ButtonOk.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.Fermer' at 20;8.", repo.FrmSglBooking.FermerInfo, new RecordItemIndex(34));
            repo.FrmSglBooking.Fermer.Click("20;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
