///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createRemarques recording.
    /// </summary>
    [TestModule("83a58307-cbab-437f-a73a-7c9a143ee080", ModuleType.Recording, 1)]
    public partial class createRemarques : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createRemarques instance = new createRemarques();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createRemarques()
        {
            voyageur = "Voyageur";
            autres = "A{LShiftKey up}utres";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createRemarques Instance
        {
            get { return instance; }
        }

#region Variables

        string _voyageur;

        /// <summary>
        /// Gets or sets the value of variable voyageur.
        /// </summary>
        [TestVariable("49dd0492-19cd-4d5f-b773-6f3805f7b72e")]
        public string voyageur
        {
            get { return _voyageur; }
            set { _voyageur = value; }
        }

        string _autres;

        /// <summary>
        /// Gets or sets the value of variable autres.
        /// </summary>
        [TestVariable("9bb8d136-1486-41a5-a37b-fcba48be91ea")]
        public string autres
        {
            get { return _autres; }
            set { _autres = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageRemarques' at 30;9.", repo.FrmSglBooking.TabPageRemarquesInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageRemarques.Click("30;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.None' at 272;14.", repo.FrmSglBooking.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.None.Click("272;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$voyageur' with focus on 'FrmSglBooking.None'.", repo.FrmSglBooking.NoneInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.None.PressKeys(voyageur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.None1' at 224;25.", repo.FrmSglBooking.None1Info, new RecordItemIndex(3));
            repo.FrmSglBooking.None1.Click("224;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$autres' with focus on 'FrmSglBooking.None1'.", repo.FrmSglBooking.None1Info, new RecordItemIndex(4));
            repo.FrmSglBooking.None1.PressKeys(autres);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
