///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createItineraire2 recording.
    /// </summary>
    [TestModule("9267b7e1-decf-46cc-a07b-2e62fb89214f", ModuleType.Recording, 1)]
    public partial class createItineraire2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createItineraire2 instance = new createItineraire2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createItineraire2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createItineraire2 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable escale.
        /// </summary>
        [TestVariable("f00c8510-ab10-4522-af26-2cfd89966f6f")]
        public string escale
        {
            get { return repo.escale; }
            set { repo.escale = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable fumeur.
        /// </summary>
        [TestVariable("27ecaf70-5e4d-4996-a1d6-5dd2830488e2")]
        public string fumeur
        {
            get { return repo.fumeur; }
            set { repo.fumeur = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable distanceMethod.
        /// </summary>
        [TestVariable("203183b0-f5ea-4a10-8f28-2ac63bced043")]
        public string distanceMethod
        {
            get { return repo.distanceMethod; }
            set { repo.distanceMethod = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageItineraire' at 25;7.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageItineraire.Click("25;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None' at 46;9.", repo.FrmSglBooking.UltraTabPageControl6.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl6.None.Click("46;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Yaoundé' with focus on 'FrmSglBooking.UltraTabPageControl6.None'.", repo.FrmSglBooking.UltraTabPageControl6.NoneInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl6.None.PressKeys("Yaoundé");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.Open' at 6;8.", repo.FrmSglBooking.UltraTabPageControl6.OpenInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl6.Open.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at 147;145.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(4));
            repo.Bora.MonthDropDownWithUIPermissions.Click("147;145");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.TextArea' at 19;8.", repo.FrmSglBooking.UltraTabPageControl61.TextAreaInfo, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl61.TextArea.Click("19;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad0}' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.TabPageItineraire.PressKeys("{NumPad1}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}{NumPad0}' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(7));
            repo.FrmSglBooking.TabPageItineraire.PressKeys("{NumPad0}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None1' at 45;7.", repo.FrmSglBooking.UltraTabPageControl6.None1Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl6.None1.Click("45;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Douala' with focus on 'FrmSglBooking.UltraTabPageControl6.None1'.", repo.FrmSglBooking.UltraTabPageControl6.None1Info, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl6.None1.PressKeys("Douala");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.Open1' at 6;9.", repo.FrmSglBooking.UltraTabPageControl6.Open1Info, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl6.Open1.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at 98;145.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(11));
            repo.Bora.MonthDropDownWithUIPermissions.Click("98;145");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.TextArea1' at 21;6.", repo.FrmSglBooking.UltraTabPageControl61.TextArea1Info, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl61.TextArea1.Click("21;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad2}{NumPad0}{NumPad0}' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(13));
            repo.FrmSglBooking.TabPageItineraire.PressKeys("{NumPad1}{NumPad2}{NumPad0}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.Open2' at 5;9.", repo.FrmSglBooking.UltraTabPageControl61.Open2Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl61.Open2.Click("5;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at 28;8.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(15));
            repo.Bora.ScrollingRegion.Click("28;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None2' at 23;8.", repo.FrmSglBooking.UltraTabPageControl6.None2Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl6.None2.Click("23;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None2'.", repo.FrmSglBooking.UltraTabPageControl6.None2Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl6.None2.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None3' at 19;9.", repo.FrmSglBooking.UltraTabPageControl6.None3Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl6.None3.Click("19;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None3'.", repo.FrmSglBooking.UltraTabPageControl6.None3Info, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl6.None3.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None4' at 16;9.", repo.FrmSglBooking.UltraTabPageControl6.None4Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl6.None4.Click("16;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None4'.", repo.FrmSglBooking.UltraTabPageControl6.None4Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl6.None4.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None5' at 23;9.", repo.FrmSglBooking.UltraTabPageControl6.None5Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl6.None5.Click("23;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None5'.", repo.FrmSglBooking.UltraTabPageControl6.None5Info, new RecordItemIndex(23));
            repo.FrmSglBooking.UltraTabPageControl6.None5.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None6' at 26;10.", repo.FrmSglBooking.UltraTabPageControl6.None6Info, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl6.None6.Click("26;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None6'.", repo.FrmSglBooking.UltraTabPageControl6.None6Info, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl6.None6.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None7' at 37;10.", repo.FrmSglBooking.UltraTabPageControl6.None7Info, new RecordItemIndex(26));
            repo.FrmSglBooking.UltraTabPageControl6.None7.Click("37;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None7'.", repo.FrmSglBooking.UltraTabPageControl6.None7Info, new RecordItemIndex(27));
            repo.FrmSglBooking.UltraTabPageControl6.None7.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None8' at 49;9.", repo.FrmSglBooking.UltraTabPageControl6.None8Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl6.None8.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None8'.", repo.FrmSglBooking.UltraTabPageControl6.None8Info, new RecordItemIndex(29));
            repo.FrmSglBooking.UltraTabPageControl6.None8.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None9' at 46;9.", repo.FrmSglBooking.UltraTabPageControl6.None9Info, new RecordItemIndex(30));
            repo.FrmSglBooking.UltraTabPageControl6.None9.Click("46;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None9'.", repo.FrmSglBooking.UltraTabPageControl6.None9Info, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl6.None9.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None10' at 38;7.", repo.FrmSglBooking.UltraTabPageControl6.None10Info, new RecordItemIndex(32));
            repo.FrmSglBooking.UltraTabPageControl6.None10.Click("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None10'.", repo.FrmSglBooking.UltraTabPageControl6.None10Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl6.None10.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None11' at 41;9.", repo.FrmSglBooking.UltraTabPageControl6.None11Info, new RecordItemIndex(34));
            repo.FrmSglBooking.UltraTabPageControl6.None11.Click("41;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None11'.", repo.FrmSglBooking.UltraTabPageControl6.None11Info, new RecordItemIndex(35));
            repo.FrmSglBooking.UltraTabPageControl6.None11.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None12' at 49;9.", repo.FrmSglBooking.UltraTabPageControl6.None12Info, new RecordItemIndex(36));
            repo.FrmSglBooking.UltraTabPageControl6.None12.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None12'.", repo.FrmSglBooking.UltraTabPageControl6.None12Info, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl6.None12.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None13' at 14;9.", repo.FrmSglBooking.UltraTabPageControl6.None13Info, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl6.None13.Click("14;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None13'.", repo.FrmSglBooking.UltraTabPageControl6.None13Info, new RecordItemIndex(39));
            repo.FrmSglBooking.UltraTabPageControl6.None13.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None14' at 8;9.", repo.FrmSglBooking.UltraTabPageControl6.None14Info, new RecordItemIndex(40));
            repo.FrmSglBooking.UltraTabPageControl6.None14.Click("8;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None14'.", repo.FrmSglBooking.UltraTabPageControl6.None14Info, new RecordItemIndex(41));
            repo.FrmSglBooking.UltraTabPageControl6.None14.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None15' at 9;8.", repo.FrmSglBooking.UltraTabPageControl6.None15Info, new RecordItemIndex(42));
            repo.FrmSglBooking.UltraTabPageControl6.None15.Click("9;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl6.None15'.", repo.FrmSglBooking.UltraTabPageControl6.None15Info, new RecordItemIndex(43));
            repo.FrmSglBooking.UltraTabPageControl6.None15.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.ChkItineraireEscale' at 6;8.", repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireEscaleInfo, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireEscale.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeur' at 6;8.", repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeurInfo, new RecordItemIndex(45));
            repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeur.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.Open3' at 5;8.", repo.FrmSglBooking.UltraTabPageControl61.Open3Info, new RecordItemIndex(46));
            repo.FrmSglBooking.UltraTabPageControl61.Open3.Click("5;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.NDCContent' at 93;10.", repo.Bora.NDCContentInfo, new RecordItemIndex(47));
            repo.Bora.NDCContent.Click("93;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
