///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createInfosGenerales2 recording.
    /// </summary>
    [TestModule("983bc5bb-3a8f-4a3d-815d-c02c150701d5", ModuleType.Recording, 1)]
    public partial class createInfosGenerales2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createInfosGenerales2 instance = new createInfosGenerales2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createInfosGenerales2()
        {
            pointDeVente = "124;6";
            dateReservation = "81;147";
            echeanceFournisseur = "78;145";
            gds = "95;9";
            recordLocator = "{NumPad1}";
            numeroDossier = "195;7";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createInfosGenerales2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _pointDeVente;

        /// <summary>
        /// Gets or sets the value of variable pointDeVente.
        /// </summary>
        [TestVariable("7cdd3175-bee1-4cd9-8d8a-b0d3dd2ed47e")]
        public string pointDeVente
        {
            get { return _pointDeVente; }
            set { _pointDeVente = value; }
        }

        string _dateReservation;

        /// <summary>
        /// Gets or sets the value of variable dateReservation.
        /// </summary>
        [TestVariable("9ceb91f0-76ba-44d9-84f4-17e7b60436ac")]
        public string dateReservation
        {
            get { return _dateReservation; }
            set { _dateReservation = value; }
        }

        string _echeanceFournisseur;

        /// <summary>
        /// Gets or sets the value of variable echeanceFournisseur.
        /// </summary>
        [TestVariable("483c50a7-15d6-48a8-9454-8d58d17f8a6c")]
        public string echeanceFournisseur
        {
            get { return _echeanceFournisseur; }
            set { _echeanceFournisseur = value; }
        }

        string _gds;

        /// <summary>
        /// Gets or sets the value of variable gds.
        /// </summary>
        [TestVariable("1479282f-7c74-49cb-ba7c-879010a49352")]
        public string gds
        {
            get { return _gds; }
            set { _gds = value; }
        }

        string _recordLocator;

        /// <summary>
        /// Gets or sets the value of variable recordLocator.
        /// </summary>
        [TestVariable("7588c744-65b0-4eef-8966-34b46912bee9")]
        public string recordLocator
        {
            get { return _recordLocator; }
            set { _recordLocator = value; }
        }

        string _numeroDossier;

        /// <summary>
        /// Gets or sets the value of variable numeroDossier.
        /// </summary>
        [TestVariable("b638f75f-ed5f-436d-a61d-76705fa94a34")]
        public string numeroDossier
        {
            get { return _numeroDossier; }
            set { _numeroDossier = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable mode.
        /// </summary>
        [TestVariable("04f1e74b-c091-4b5f-9d3e-29f1257275b2")]
        public string mode
        {
            get { return repo.mode; }
            set { repo.mode = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable transaction.
        /// </summary>
        [TestVariable("5366146b-93e4-41c9-9f3b-d3be42cc08d9")]
        public string transaction
        {
            get { return repo.transaction; }
            set { repo.transaction = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 48;9.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.BtnOk.Click("48;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open' at 5;6.", repo.FrmSglBooking.UltraTabPageControl1.OpenInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl1.Open.Click("5;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $pointDeVente.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(2));
            repo.Bora.ScrollingRegion.Click(pointDeVente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 29;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.BtnOk.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open1' at 6;8.", repo.FrmSglBooking.UltraTabPageControl1.Open1Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl1.Open1.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.DISTRIBUTION' at 90;9.", repo.Bora.DISTRIBUTIONInfo, new RecordItemIndex(5));
            repo.Bora.DISTRIBUTION.Click("90;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 19;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.BtnOk.Click("19;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open2' at 5;8.", repo.FrmSglBooking.UltraTabPageControl1.Open2Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl1.Open2.Click("5;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.VENTE' at 89;9.", repo.Bora.VENTEInfo, new RecordItemIndex(8));
            repo.Bora.VENTE.Click("89;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown' at 9;7.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDownInfo, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown.Click("9;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open' at 6;10.", repo.Bora.OpenInfo, new RecordItemIndex(10));
            repo.Bora.Open.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $dateReservation.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(11));
            repo.Bora.MonthDropDownWithUIPermissions.Click(dateReservation);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open1' at 7;9.", repo.Bora.Open1Info, new RecordItemIndex(12));
            repo.Bora.Open1.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $echeanceFournisseur.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(13));
            repo.Bora.MonthDropDownWithUIPermissions.Click(echeanceFournisseur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open4' at 7;7.", repo.FrmSglBooking.UltraTabPageControl1.Open4Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl1.Open4.Click("7;7");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open4' at 7;7.", repo.FrmSglBooking.UltraTabPageControl1.Open4Info, new RecordItemIndex(15));
            //repo.FrmSglBooking.UltraTabPageControl1.Open4.Click("7;7");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $gds.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(16));
            repo.Bora.ScrollingRegion.Click(gds);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open14' at 8;7.", repo.FrmSglBooking.UltraTabPageControl1.Open14Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl1.Open14.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion1' at 189;7.", repo.Bora.ScrollingRegion1Info, new RecordItemIndex(18));
            repo.Bora.ScrollingRegion1.Click("189;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ContainerTransaction' at 325;147.", repo.FrmSglBooking.UltraTabPageControl1.ContainerTransactionInfo, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl1.ContainerTransaction.Click("325;147");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown1' at 16;9.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1.Click("16;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open2' at 6;8.", repo.Bora.Open2Info, new RecordItemIndex(21));
            repo.Bora.Open2.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ContainerTransaction' at 327;197.", repo.FrmSglBooking.UltraTabPageControl1.ContainerTransactionInfo, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl1.ContainerTransaction.Click("327;197");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None' at 40;9.", repo.FrmSglBooking.UltraTabPageControl1.NoneInfo, new RecordItemIndex(23));
            repo.FrmSglBooking.UltraTabPageControl1.None.Click("40;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$recordLocator' with focus on 'FrmSglBooking.UltraTabPageControl1.None'.", repo.FrmSglBooking.UltraTabPageControl1.NoneInfo, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl1.None.PressKeys(recordLocator);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ComboBox' at 208;10.", repo.FrmSglBooking.UltraTabPageControl1.ComboBoxInfo, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl1.ComboBox.Click("208;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $numeroDossier.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(26));
            repo.Bora.ScrollingRegion.Click(numeroDossier);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
