///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createFees recording.
    /// </summary>
    [TestModule("e5218156-cfba-4903-939b-addc34e71497", ModuleType.Recording, 1)]
    public partial class createFees : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createFees instance = new createFees();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createFees()
        {
            fraisDivers1 = "{NumPad1}";
            fraisDivers2 = "{NumPad1}";
            fraisDivers3 = "{NumPad1}";
            fraisDivers4 = "{NumPad1}";
            fraisDivers5 = "{NumPad1}";
            fraisMasques = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createFees Instance
        {
            get { return instance; }
        }

#region Variables

        string _fraisDivers1;

        /// <summary>
        /// Gets or sets the value of variable fraisDivers1.
        /// </summary>
        [TestVariable("46e5cdb0-efe8-4046-8468-489f7774b1b3")]
        public string fraisDivers1
        {
            get { return _fraisDivers1; }
            set { _fraisDivers1 = value; }
        }

        string _fraisDivers2;

        /// <summary>
        /// Gets or sets the value of variable fraisDivers2.
        /// </summary>
        [TestVariable("158a433a-5c4f-4af1-a125-fd2ce7385c39")]
        public string fraisDivers2
        {
            get { return _fraisDivers2; }
            set { _fraisDivers2 = value; }
        }

        string _fraisDivers3;

        /// <summary>
        /// Gets or sets the value of variable fraisDivers3.
        /// </summary>
        [TestVariable("d332b058-b0bb-4a12-a786-cdedb230ee07")]
        public string fraisDivers3
        {
            get { return _fraisDivers3; }
            set { _fraisDivers3 = value; }
        }

        string _fraisDivers4;

        /// <summary>
        /// Gets or sets the value of variable fraisDivers4.
        /// </summary>
        [TestVariable("027f10b2-c849-4709-be10-3e0d1a6fe917")]
        public string fraisDivers4
        {
            get { return _fraisDivers4; }
            set { _fraisDivers4 = value; }
        }

        string _fraisDivers5;

        /// <summary>
        /// Gets or sets the value of variable fraisDivers5.
        /// </summary>
        [TestVariable("09547447-e768-4e23-812b-995e29395f4b")]
        public string fraisDivers5
        {
            get { return _fraisDivers5; }
            set { _fraisDivers5 = value; }
        }

        string _fraisMasques;

        /// <summary>
        /// Gets or sets the value of variable fraisMasques.
        /// </summary>
        [TestVariable("a9d30db5-6501-4974-8671-340c20005aa1")]
        public string fraisMasques
        {
            get { return _fraisMasques; }
            set { _fraisMasques = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageFees' at 33;9.", repo.FrmSglBooking.TabPageFeesInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageFees.Click("33;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None' at 44;10.", repo.FrmSglBooking.UltraTabPageControl7.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl7.None.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None1' at 43;10.", repo.FrmSglBooking.UltraTabPageControl7.None1Info, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl7.None1.Click("43;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl7.None1'.", repo.FrmSglBooking.UltraTabPageControl7.None1Info, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl7.None1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None2' at 44;12.", repo.FrmSglBooking.UltraTabPageControl7.None2Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl7.None2.Click("44;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None3' at 46;11.", repo.FrmSglBooking.UltraTabPageControl7.None3Info, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl7.None3.Click("46;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None4' at 52;10.", repo.FrmSglBooking.UltraTabPageControl7.None4Info, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl7.None4.Click("52;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None5' at 63;11.", repo.FrmSglBooking.UltraTabPageControl7.None5Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl7.None5.Click("63;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None6' at 71;10.", repo.FrmSglBooking.UltraTabPageControl7.None6Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl7.None6.Click("71;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisDivers1' with focus on 'FrmSglBooking.UltraTabPageControl7.None6'.", repo.FrmSglBooking.UltraTabPageControl7.None6Info, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl7.None6.PressKeys(fraisDivers1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None7' at 76;11.", repo.FrmSglBooking.UltraTabPageControl7.None7Info, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl7.None7.Click("76;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisDivers2' with focus on 'FrmSglBooking.UltraTabPageControl7.None7'.", repo.FrmSglBooking.UltraTabPageControl7.None7Info, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl7.None7.PressKeys(fraisDivers2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None8' at 88;11.", repo.FrmSglBooking.UltraTabPageControl7.None8Info, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl7.None8.Click("88;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisDivers3' with focus on 'FrmSglBooking.UltraTabPageControl7.None8'.", repo.FrmSglBooking.UltraTabPageControl7.None8Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl7.None8.PressKeys(fraisDivers3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None9' at 116;10.", repo.FrmSglBooking.UltraTabPageControl7.None9Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl7.None9.Click("116;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None10' at 120;10.", repo.FrmSglBooking.UltraTabPageControl7.None10Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl7.None10.Click("120;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None11' at 121;11.", repo.FrmSglBooking.UltraTabPageControl7.None11Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl7.None11.Click("121;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None12' at 121;9.", repo.FrmSglBooking.UltraTabPageControl7.None12Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl7.None12.Click("121;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None13' at 123;10.", repo.FrmSglBooking.UltraTabPageControl7.None13Info, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl7.None13.Click("123;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None14' at 120;10.", repo.FrmSglBooking.UltraTabPageControl7.None14Info, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl7.None14.Click("120;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None15' at 75;9.", repo.FrmSglBooking.UltraTabPageControl7.None15Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl7.None15.Click("75;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisDivers4' with focus on 'FrmSglBooking.UltraTabPageControl7.None15'.", repo.FrmSglBooking.UltraTabPageControl7.None15Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl7.None15.PressKeys(fraisDivers4);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None16' at 76;9.", repo.FrmSglBooking.UltraTabPageControl7.None16Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl7.None16.Click("76;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisDivers5' with focus on 'FrmSglBooking.UltraTabPageControl7.None16'.", repo.FrmSglBooking.UltraTabPageControl7.None16Info, new RecordItemIndex(23));
            repo.FrmSglBooking.UltraTabPageControl7.None16.PressKeys(fraisDivers5);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl7.None17' at 79;10.", repo.FrmSglBooking.UltraTabPageControl7.None17Info, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl7.None17.Click("79;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fraisMasques' with focus on 'FrmSglBooking.UltraTabPageControl7.None17'.", repo.FrmSglBooking.UltraTabPageControl7.None17Info, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl7.None17.PressKeys(fraisMasques);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
