///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createInfosGenerales4 recording.
    /// </summary>
    [TestModule("a522b3ac-ab23-46f9-8e46-8891defae672", ModuleType.Recording, 1)]
    public partial class createInfosGenerales4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createInfosGenerales4 instance = new createInfosGenerales4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createInfosGenerales4()
        {
            dateDeTransaction = "156;146";
            nomClient2 = "200;26";
            nomVoyageur = "170;9";
            depart = "116;146";
            retour = "116;146";
            numeroBillet = "{NumPad1}";
            itineraire = "{NumPad1}";
            ticketingAgent2 = "75;26";
            cash2 = "{NumPad3},{NumPad7}{NumPad8}";
            id = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createInfosGenerales4 Instance
        {
            get { return instance; }
        }

#region Variables

        string _dateDeTransaction;

        /// <summary>
        /// Gets or sets the value of variable dateDeTransaction.
        /// </summary>
        [TestVariable("832a1449-8824-44fd-bb66-6bbb6466eecc")]
        public string dateDeTransaction
        {
            get { return _dateDeTransaction; }
            set { _dateDeTransaction = value; }
        }

        string _nomClient2;

        /// <summary>
        /// Gets or sets the value of variable nomClient2.
        /// </summary>
        [TestVariable("bbe41dd2-3b2a-4157-8a41-0059adea9406")]
        public string nomClient2
        {
            get { return _nomClient2; }
            set { _nomClient2 = value; }
        }

        string _nomVoyageur;

        /// <summary>
        /// Gets or sets the value of variable nomVoyageur.
        /// </summary>
        [TestVariable("f9c048a5-7cdf-4c8f-86c1-836761680565")]
        public string nomVoyageur
        {
            get { return _nomVoyageur; }
            set { _nomVoyageur = value; }
        }

        string _depart;

        /// <summary>
        /// Gets or sets the value of variable depart.
        /// </summary>
        [TestVariable("5faa1c77-5ae1-4ee3-a9f8-41578df2e093")]
        public string depart
        {
            get { return _depart; }
            set { _depart = value; }
        }

        string _retour;

        /// <summary>
        /// Gets or sets the value of variable retour.
        /// </summary>
        [TestVariable("3947c334-7dc3-4300-8d4b-851cb6d121d2")]
        public string retour
        {
            get { return _retour; }
            set { _retour = value; }
        }

        string _numeroBillet;

        /// <summary>
        /// Gets or sets the value of variable numeroBillet.
        /// </summary>
        [TestVariable("e3c44f71-6a2d-4730-837d-622230caf790")]
        public string numeroBillet
        {
            get { return _numeroBillet; }
            set { _numeroBillet = value; }
        }

        string _itineraire;

        /// <summary>
        /// Gets or sets the value of variable itineraire.
        /// </summary>
        [TestVariable("af8e8406-69c6-4dc2-aab1-1db6ca672516")]
        public string itineraire
        {
            get { return _itineraire; }
            set { _itineraire = value; }
        }

        string _ticketingAgent2;

        /// <summary>
        /// Gets or sets the value of variable ticketingAgent2.
        /// </summary>
        [TestVariable("c4052a8d-bde3-47a5-9ecd-63abfcd2860b")]
        public string ticketingAgent2
        {
            get { return _ticketingAgent2; }
            set { _ticketingAgent2 = value; }
        }

        string _cash2;

        /// <summary>
        /// Gets or sets the value of variable cash2.
        /// </summary>
        [TestVariable("856109e1-7426-4e84-9426-638d00287d5d")]
        public string cash2
        {
            get { return _cash2; }
            set { _cash2 = value; }
        }

        string _id;

        /// <summary>
        /// Gets or sets the value of variable id.
        /// </summary>
        [TestVariable("f5fac3d8-fb24-40bd-bde4-7694e0afc7a5")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable typeDocument2.
        /// </summary>
        [TestVariable("1164f69a-9d74-4f4b-8864-0f6c2fc34b96")]
        public string typeDocument2
        {
            get { return repo.typeDocument2; }
            set { repo.typeDocument2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable classeResa.
        /// </summary>
        [TestVariable("61b48ddd-98bf-4f26-bf62-cb1a174cdc87")]
        public string classeResa
        {
            get { return repo.classeResa; }
            set { repo.classeResa = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable destination.
        /// </summary>
        [TestVariable("13b82235-a865-4290-9695-2621351de07f")]
        public string destination
        {
            get { return repo.destination; }
            set { repo.destination = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageInfosGenerales' at 54;8.", repo.FrmSglBooking.TabPageInfosGeneralesInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageInfosGenerales.Click("54;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 26;13.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.BtnOk.Click("26;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 24;12.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(2));
            repo.BoraMessageBox.ButtonOk.Click("24;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 41;14.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.BtnOk.Click("41;14");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSelectionnerLeTypeDeDocumen(repo.BoraMessageBox.VeuillezSelectionnerLeTypeDeDocumenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 40;8.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(5));
            repo.BoraMessageBox.ButtonOk.Click("40;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp' at 14;9.", repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXpInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl1.UtxbVoyageurXp.Click("14;9");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(7));
            //repo.FrmSglBooking.Self.EnsureVisible();
            //Keyboard.Press(" ");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.CellATB' at 16;6.", repo.Bora.CellATBInfo, new RecordItemIndex(8));
            repo.Bora.CellATB.Click("16;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 34;5.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(9));
            repo.FrmSglBooking.BtnOk.Click("34;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 35;12.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(10));
            repo.BoraMessageBox.ButtonOk.Click("35;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 25;9.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.BtnOk.Click("25;9");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSaisirLaDateDeTransaction(repo.BoraMessageBox.VeuillezSaisirLaDateDeTransactionInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 38;9.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(13));
            repo.BoraMessageBox.ButtonOk.Click("38;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open3' at 6;9.", repo.FrmSglBooking.UltraTabPageControl1.Open3Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl1.Open3.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $dateDeTransaction.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(15));
            repo.Bora.MonthDropDownWithUIPermissions.Click(dateDeTransaction);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 33;12.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(16));
            repo.FrmSglBooking.BtnOk.Click("33;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 41;9.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(17));
            repo.BoraMessageBox.ButtonOk.Click("41;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 46;10.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(18));
            repo.FrmSglBooking.BtnOk.Click("46;10");
            Delay.Milliseconds(0);
            
            Validate_VeuillezRenseignerLeNomDuVoyageur(repo.BoraMessageBox.VeuillezRenseignerLeNomDuVoyageurInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 41;7.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(20));
            repo.BoraMessageBox.ButtonOk.Click("41;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.ButtonDropDown1' at 5;8.", repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl1.ButtonDropDown1.Click("5;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open7' at 7;7.", repo.FrmSglBooking.UltraTabPageControl1.Open7Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl1.Open7.Click("7;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomClient2.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(23));
            repo.Bora.ScrollingRegion.Click(nomClient2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open8' at 7;8.", repo.FrmSglBooking.UltraTabPageControl1.Open8Info, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl1.Open8.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $nomVoyageur.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(25));
            repo.Bora.ScrollingRegion.Click(nomVoyageur);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 16;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(26));
            repo.FrmSglBooking.BtnOk.Click("16;11");
            Delay.Milliseconds(0);
            
            Validate_VeuillezRenseignerLaClasseDeReserva(repo.BoraMessageBox.VeuillezRenseignerLaClasseDeReservaInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 40;9.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(28));
            repo.BoraMessageBox.ButtonOk.Click("40;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.First' at 71;10.", repo.Bora.FirstInfo, new RecordItemIndex(29));
            repo.Bora.First.Click("71;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 32;10.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(30));
            repo.FrmSglBooking.BtnOk.Click("32;10");
            Delay.Milliseconds(0);
            
            Validate_VeuilleSaisirLaDateDepart(repo.BoraMessageBox.VeuilleSaisirLaDateDepartInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 44;12.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(32));
            repo.BoraMessageBox.ButtonOk.Click("44;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open15' at 8;8.", repo.FrmSglBooking.UltraTabPageControl1.Open15Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl1.Open15.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $depart.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(34));
            repo.Bora.MonthDropDownWithUIPermissions.Click(depart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 43;13.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(35));
            repo.FrmSglBooking.BtnOk.Click("43;13");
            Delay.Milliseconds(0);
            
            Validate_VeuilleSaisirLaDateRetour(repo.BoraMessageBox.VeuilleSaisirLaDateRetourInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 30;8.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(37));
            repo.BoraMessageBox.ButtonOk.Click("30;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.Open15' at 6;6.", repo.FrmSglBooking.UltraTabPageControl1.Open15Info, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl1.Open15.Click("6;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $retour.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(39));
            repo.Bora.MonthDropDownWithUIPermissions.Click(retour);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 51;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(40));
            repo.FrmSglBooking.BtnOk.Click("51;11");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSaisirLeNumeroDuBillet(repo.BoraMessageBox.VeuillezSaisirLeNumeroDuBilletInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 38;7.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(42));
            repo.BoraMessageBox.ButtonOk.Click("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl1.None1' at 37;10.", repo.FrmSglBooking.UltraTabPageControl1.None1Info, new RecordItemIndex(43));
            repo.FrmSglBooking.UltraTabPageControl1.None1.Click("37;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroBillet' with focus on 'FrmSglBooking.UltraTabPageControl1.None1'.", repo.FrmSglBooking.UltraTabPageControl1.None1Info, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl1.None1.PressKeys(numeroBillet);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 31;13.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(45));
            repo.FrmSglBooking.BtnOk.Click("31;13");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSaisirLItineraire(repo.BoraMessageBox.VeuillezSaisirLItineraireInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 38;10.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(47));
            repo.BoraMessageBox.ButtonOk.Click("38;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$itineraire' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(48));
            repo.FrmSglBooking.Self.EnsureVisible();
            Keyboard.Press(itineraire);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 35;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(49));
            repo.FrmSglBooking.BtnOk.Click("35;11");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSelectionnerLaDestination(repo.BoraMessageBox.VeuillezSelectionnerLaDestinationInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 49;11.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(51));
            repo.BoraMessageBox.ButtonOk.Click("49;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.Open3' at 7;9.", repo.Bora.Open3Info, new RecordItemIndex(52));
            repo.Bora.Open3.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItemIN' at 84;8.", repo.Bora.ListItemINInfo, new RecordItemIndex(53));
            repo.Bora.ListItemIN.Click("84;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 37;12.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(54));
            repo.FrmSglBooking.BtnOk.Click("37;12");
            Delay.Milliseconds(0);
            
            Validate_VeuillezSelectionnerLeTicketingAgent(repo.BoraMessageBox.VeuillezSelectionnerLeTicketingAgentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 42;13.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(56));
            repo.BoraMessageBox.ButtonOk.Click("42;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $ticketingAgent2.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(57));
            repo.Bora.ScrollingRegion.Click(ticketingAgent2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.BtnOk' at 25;11.", repo.FrmSglBooking.BtnOkInfo, new RecordItemIndex(58));
            repo.FrmSglBooking.BtnOk.Click("25;11");
            Delay.Milliseconds(0);
            
            Validate_AjoutImpossibleLeNetAFacturerEst(repo.BoraMessageBox.AjoutImpossibleLeNetAFacturerEstInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BoraMessageBox.ButtonOk' at 17;6.", repo.BoraMessageBox.ButtonOkInfo, new RecordItemIndex(60));
            repo.BoraMessageBox.ButtonOk.Click("17;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$cash2' with focus on 'FrmSglBooking'.", repo.FrmSglBooking.SelfInfo, new RecordItemIndex(61));
            repo.FrmSglBooking.Self.PressKeys(cash2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.Fermer' at 22;11.", repo.FrmSglBooking.FermerInfo, new RecordItemIndex(62));
            repo.FrmSglBooking.Fermer.Click("22;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
