///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createItineraire recording.
    /// </summary>
    [TestModule("dd7fc67c-25ee-47c0-b884-aa890993eace", ModuleType.Recording, 1)]
    public partial class createItineraire : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createItineraire instance = new createItineraire();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createItineraire()
        {
            villeDepart = "Yaoundé";
            dateDepart = "127;146";
            heureDepart = "{NumPad1}{NumPad0}{NumPad0}{NumPad0}";
            villeArrivee = "D{LShiftKey up}ouala";
            dateArrivee = "93;148";
            heureArrivee = "{NumPad1}{NumPad2}{NumPad0}{NumPad0}";
            Cie = "35;8";
            numeroVol = "{NumPad1}";
            terminalDepart = "{NumPad1}";
            checkin = "{NumPad1}";
            stops = "{NumPad1}";
            classe = "{NumPad1}";
            equipement = "{NumPad1}";
            terminalArrivee = "{NumPad1}";
            dureeVol = "{NumPad1}";
            mileage = "{NumPad1}";
            repas = "{NumPad1}";
            franchise = "{NumPad1}";
            codeShare = "{NumPad1}";
            fareBasis = "{NumPad1}";
            legPrice = "{NumPad1}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createItineraire Instance
        {
            get { return instance; }
        }

#region Variables

        string _villeDepart;

        /// <summary>
        /// Gets or sets the value of variable villeDepart.
        /// </summary>
        [TestVariable("774f7c48-fdf4-453d-9ac4-0c3ef794c0c7")]
        public string villeDepart
        {
            get { return _villeDepart; }
            set { _villeDepart = value; }
        }

        string _dateDepart;

        /// <summary>
        /// Gets or sets the value of variable dateDepart.
        /// </summary>
        [TestVariable("1d1cc8f8-64d0-4b3b-ba99-be998ec7c7cb")]
        public string dateDepart
        {
            get { return _dateDepart; }
            set { _dateDepart = value; }
        }

        string _heureDepart;

        /// <summary>
        /// Gets or sets the value of variable heureDepart.
        /// </summary>
        [TestVariable("7b515171-aaf0-4ed6-bbe5-d0fb0e84a4c9")]
        public string heureDepart
        {
            get { return _heureDepart; }
            set { _heureDepart = value; }
        }

        string _villeArrivee;

        /// <summary>
        /// Gets or sets the value of variable villeArrivee.
        /// </summary>
        [TestVariable("2599e24b-f5a4-4f79-8bb6-38997fd9a070")]
        public string villeArrivee
        {
            get { return _villeArrivee; }
            set { _villeArrivee = value; }
        }

        string _dateArrivee;

        /// <summary>
        /// Gets or sets the value of variable dateArrivee.
        /// </summary>
        [TestVariable("55b18eaf-1746-40d4-90df-f25a0a540f68")]
        public string dateArrivee
        {
            get { return _dateArrivee; }
            set { _dateArrivee = value; }
        }

        string _heureArrivee;

        /// <summary>
        /// Gets or sets the value of variable heureArrivee.
        /// </summary>
        [TestVariable("147866f1-0924-457a-8ff0-1ecd950effa5")]
        public string heureArrivee
        {
            get { return _heureArrivee; }
            set { _heureArrivee = value; }
        }

        string _Cie;

        /// <summary>
        /// Gets or sets the value of variable Cie.
        /// </summary>
        [TestVariable("901e3ac0-b428-42bb-a7dd-e8c52e78fcd9")]
        public string Cie
        {
            get { return _Cie; }
            set { _Cie = value; }
        }

        string _numeroVol;

        /// <summary>
        /// Gets or sets the value of variable numeroVol.
        /// </summary>
        [TestVariable("2487af2f-c2d7-4636-bb0f-7695db41f5a5")]
        public string numeroVol
        {
            get { return _numeroVol; }
            set { _numeroVol = value; }
        }

        string _terminalDepart;

        /// <summary>
        /// Gets or sets the value of variable terminalDepart.
        /// </summary>
        [TestVariable("2d514284-b32e-45b8-a2ed-d5a50e8343b1")]
        public string terminalDepart
        {
            get { return _terminalDepart; }
            set { _terminalDepart = value; }
        }

        string _checkin;

        /// <summary>
        /// Gets or sets the value of variable checkin.
        /// </summary>
        [TestVariable("545156e0-02f1-4169-9003-5a4d610eae42")]
        public string checkin
        {
            get { return _checkin; }
            set { _checkin = value; }
        }

        string _stops;

        /// <summary>
        /// Gets or sets the value of variable stops.
        /// </summary>
        [TestVariable("8a4977d6-1f70-4621-998e-5ba6bf35d76d")]
        public string stops
        {
            get { return _stops; }
            set { _stops = value; }
        }

        string _classe;

        /// <summary>
        /// Gets or sets the value of variable classe.
        /// </summary>
        [TestVariable("e0c21e81-76f9-4bad-adcb-c18dd619566b")]
        public string classe
        {
            get { return _classe; }
            set { _classe = value; }
        }

        string _equipement;

        /// <summary>
        /// Gets or sets the value of variable equipement.
        /// </summary>
        [TestVariable("eb3ec6b1-a81b-479e-ba53-47b101233ac2")]
        public string equipement
        {
            get { return _equipement; }
            set { _equipement = value; }
        }

        string _terminalArrivee;

        /// <summary>
        /// Gets or sets the value of variable terminalArrivee.
        /// </summary>
        [TestVariable("8fb8b957-31f1-4931-a7d5-1254eacdfa26")]
        public string terminalArrivee
        {
            get { return _terminalArrivee; }
            set { _terminalArrivee = value; }
        }

        string _dureeVol;

        /// <summary>
        /// Gets or sets the value of variable dureeVol.
        /// </summary>
        [TestVariable("a4232742-4f91-4ba3-9228-55a46d8d4be0")]
        public string dureeVol
        {
            get { return _dureeVol; }
            set { _dureeVol = value; }
        }

        string _mileage;

        /// <summary>
        /// Gets or sets the value of variable mileage.
        /// </summary>
        [TestVariable("80c5e8b0-af90-4985-b899-29356aa8c59e")]
        public string mileage
        {
            get { return _mileage; }
            set { _mileage = value; }
        }

        string _repas;

        /// <summary>
        /// Gets or sets the value of variable repas.
        /// </summary>
        [TestVariable("9fc33428-5683-47c2-8a1a-1ef0b91a9961")]
        public string repas
        {
            get { return _repas; }
            set { _repas = value; }
        }

        string _franchise;

        /// <summary>
        /// Gets or sets the value of variable franchise.
        /// </summary>
        [TestVariable("dd2763d6-2c5a-45bc-b405-a49c95126959")]
        public string franchise
        {
            get { return _franchise; }
            set { _franchise = value; }
        }

        string _codeShare;

        /// <summary>
        /// Gets or sets the value of variable codeShare.
        /// </summary>
        [TestVariable("ed859f6b-58c3-42e6-9258-89ce39190ea1")]
        public string codeShare
        {
            get { return _codeShare; }
            set { _codeShare = value; }
        }

        string _fareBasis;

        /// <summary>
        /// Gets or sets the value of variable fareBasis.
        /// </summary>
        [TestVariable("7475a713-3ec0-443b-a5eb-8406d3b5f4e1")]
        public string fareBasis
        {
            get { return _fareBasis; }
            set { _fareBasis = value; }
        }

        string _legPrice;

        /// <summary>
        /// Gets or sets the value of variable legPrice.
        /// </summary>
        [TestVariable("647bc54e-7946-456c-a471-bcbcebf6196e")]
        public string legPrice
        {
            get { return _legPrice; }
            set { _legPrice = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable escale.
        /// </summary>
        [TestVariable("f00c8510-ab10-4522-af26-2cfd89966f6f")]
        public string escale
        {
            get { return repo.escale; }
            set { repo.escale = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable fumeur.
        /// </summary>
        [TestVariable("27ecaf70-5e4d-4996-a1d6-5dd2830488e2")]
        public string fumeur
        {
            get { return repo.fumeur; }
            set { repo.fumeur = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable distanceMethod.
        /// </summary>
        [TestVariable("203183b0-f5ea-4a10-8f28-2ac63bced043")]
        public string distanceMethod
        {
            get { return repo.distanceMethod; }
            set { repo.distanceMethod = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageItineraire' at 21;8.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageItineraire.Click("21;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None' at 13;8.", repo.FrmSglBooking.UltraTabPageControl6.NoneInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl6.None.Click("13;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$villeDepart' with focus on 'FrmSglBooking.UltraTabPageControl6.None'.", repo.FrmSglBooking.UltraTabPageControl6.NoneInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl6.None.PressKeys(villeDepart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.Open' at 6;9.", repo.FrmSglBooking.UltraTabPageControl6.OpenInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl6.Open.Click("6;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $dateDepart.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(4));
            repo.Bora.MonthDropDownWithUIPermissions.Click(dateDepart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.TextArea' at 24;6.", repo.FrmSglBooking.UltraTabPageControl61.TextAreaInfo, new RecordItemIndex(5));
            repo.FrmSglBooking.UltraTabPageControl61.TextArea.Click("24;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$heureDepart' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.TabPageItineraire.PressKeys(heureDepart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None1' at 43;10.", repo.FrmSglBooking.UltraTabPageControl6.None1Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl6.None1.Click("43;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$villeArrivee' with focus on 'FrmSglBooking.UltraTabPageControl6.None1'.", repo.FrmSglBooking.UltraTabPageControl6.None1Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl6.None1.PressKeys(villeArrivee);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.Open1' at 7;7.", repo.FrmSglBooking.UltraTabPageControl6.Open1Info, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl6.Open1.Click("7;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.MonthDropDownWithUIPermissions' at position from variable $dateArrivee.", repo.Bora.MonthDropDownWithUIPermissionsInfo, new RecordItemIndex(10));
            repo.Bora.MonthDropDownWithUIPermissions.Click(dateArrivee);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.TextArea1' at 27;6.", repo.FrmSglBooking.UltraTabPageControl61.TextArea1Info, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl61.TextArea1.Click("27;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left}' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(12));
            repo.FrmSglBooking.TabPageItineraire.PressKeys("{Left}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$heureArrivee' with focus on 'FrmSglBooking.TabPageItineraire'.", repo.FrmSglBooking.TabPageItineraireInfo, new RecordItemIndex(13));
            repo.FrmSglBooking.TabPageItineraire.PressKeys(heureArrivee);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.Open2' at 8;8.", repo.FrmSglBooking.UltraTabPageControl61.Open2Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl61.Open2.Click("8;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion' at position from variable $Cie.", repo.Bora.ScrollingRegionInfo, new RecordItemIndex(15));
            repo.Bora.ScrollingRegion.Click(Cie);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None2' at 25;10.", repo.FrmSglBooking.UltraTabPageControl6.None2Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl6.None2.Click("25;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$numeroVol' with focus on 'FrmSglBooking.UltraTabPageControl6.None2'.", repo.FrmSglBooking.UltraTabPageControl6.None2Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl6.None2.PressKeys(numeroVol);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.VilleArrivee' at 11;9.", repo.FrmSglBooking.UltraTabPageControl6.VilleArriveeInfo, new RecordItemIndex(18));
            repo.FrmSglBooking.UltraTabPageControl6.VilleArrivee.Click("11;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment' at 302;1.", repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegmentInfo, new RecordItemIndex(19));
            repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment.Click("302;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None3' at 49;11.", repo.FrmSglBooking.UltraTabPageControl6.None3Info, new RecordItemIndex(20));
            repo.FrmSglBooking.UltraTabPageControl6.None3.Click("49;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$terminalDepart' with focus on 'FrmSglBooking.UltraTabPageControl6.None3'.", repo.FrmSglBooking.UltraTabPageControl6.None3Info, new RecordItemIndex(21));
            repo.FrmSglBooking.UltraTabPageControl6.None3.PressKeys(terminalDepart);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None4' at 40;9.", repo.FrmSglBooking.UltraTabPageControl6.None4Info, new RecordItemIndex(22));
            repo.FrmSglBooking.UltraTabPageControl6.None4.Click("40;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$checkin' with focus on 'FrmSglBooking.UltraTabPageControl6.None4'.", repo.FrmSglBooking.UltraTabPageControl6.None4Info, new RecordItemIndex(23));
            repo.FrmSglBooking.UltraTabPageControl6.None4.PressKeys(checkin);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None5' at 39;9.", repo.FrmSglBooking.UltraTabPageControl6.None5Info, new RecordItemIndex(24));
            repo.FrmSglBooking.UltraTabPageControl6.None5.Click("39;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$stops' with focus on 'FrmSglBooking.UltraTabPageControl6.None5'.", repo.FrmSglBooking.UltraTabPageControl6.None5Info, new RecordItemIndex(25));
            repo.FrmSglBooking.UltraTabPageControl6.None5.PressKeys(stops);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None6' at 39;10.", repo.FrmSglBooking.UltraTabPageControl6.None6Info, new RecordItemIndex(26));
            repo.FrmSglBooking.UltraTabPageControl6.None6.Click("39;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$classe' with focus on 'FrmSglBooking.UltraTabPageControl6.None6'.", repo.FrmSglBooking.UltraTabPageControl6.None6Info, new RecordItemIndex(27));
            repo.FrmSglBooking.UltraTabPageControl6.None6.PressKeys(classe);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None7' at 37;12.", repo.FrmSglBooking.UltraTabPageControl6.None7Info, new RecordItemIndex(28));
            repo.FrmSglBooking.UltraTabPageControl6.None7.Click("37;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$equipement' with focus on 'FrmSglBooking.UltraTabPageControl6.None7'.", repo.FrmSglBooking.UltraTabPageControl6.None7Info, new RecordItemIndex(29));
            repo.FrmSglBooking.UltraTabPageControl6.None7.PressKeys(equipement);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None8' at 28;9.", repo.FrmSglBooking.UltraTabPageControl6.None8Info, new RecordItemIndex(30));
            repo.FrmSglBooking.UltraTabPageControl6.None8.Click("28;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$terminalArrivee' with focus on 'FrmSglBooking.UltraTabPageControl6.None8'.", repo.FrmSglBooking.UltraTabPageControl6.None8Info, new RecordItemIndex(31));
            repo.FrmSglBooking.UltraTabPageControl6.None8.PressKeys(terminalArrivee);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None9' at 28;9.", repo.FrmSglBooking.UltraTabPageControl6.None9Info, new RecordItemIndex(32));
            repo.FrmSglBooking.UltraTabPageControl6.None9.Click("28;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$dureeVol' with focus on 'FrmSglBooking.UltraTabPageControl6.None9'.", repo.FrmSglBooking.UltraTabPageControl6.None9Info, new RecordItemIndex(33));
            repo.FrmSglBooking.UltraTabPageControl6.None9.PressKeys(dureeVol);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None10' at 29;10.", repo.FrmSglBooking.UltraTabPageControl6.None10Info, new RecordItemIndex(34));
            repo.FrmSglBooking.UltraTabPageControl6.None10.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$mileage' with focus on 'FrmSglBooking.UltraTabPageControl6.None10'.", repo.FrmSglBooking.UltraTabPageControl6.None10Info, new RecordItemIndex(35));
            repo.FrmSglBooking.UltraTabPageControl6.None10.PressKeys(mileage);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None11' at 28;9.", repo.FrmSglBooking.UltraTabPageControl6.None11Info, new RecordItemIndex(36));
            repo.FrmSglBooking.UltraTabPageControl6.None11.Click("28;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$repas' with focus on 'FrmSglBooking.UltraTabPageControl6.None11'.", repo.FrmSglBooking.UltraTabPageControl6.None11Info, new RecordItemIndex(37));
            repo.FrmSglBooking.UltraTabPageControl6.None11.PressKeys(repas);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None12' at 25;9.", repo.FrmSglBooking.UltraTabPageControl6.None12Info, new RecordItemIndex(38));
            repo.FrmSglBooking.UltraTabPageControl6.None12.Click("25;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$franchise' with focus on 'FrmSglBooking.UltraTabPageControl6.None12'.", repo.FrmSglBooking.UltraTabPageControl6.None12Info, new RecordItemIndex(39));
            repo.FrmSglBooking.UltraTabPageControl6.None12.PressKeys(franchise);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None13' at 25;9.", repo.FrmSglBooking.UltraTabPageControl6.None13Info, new RecordItemIndex(40));
            repo.FrmSglBooking.UltraTabPageControl6.None13.Click("25;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$codeShare' with focus on 'FrmSglBooking.UltraTabPageControl6.None13'.", repo.FrmSglBooking.UltraTabPageControl6.None13Info, new RecordItemIndex(41));
            repo.FrmSglBooking.UltraTabPageControl6.None13.PressKeys(codeShare);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None14' at 14;10.", repo.FrmSglBooking.UltraTabPageControl6.None14Info, new RecordItemIndex(42));
            repo.FrmSglBooking.UltraTabPageControl6.None14.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$fareBasis' with focus on 'FrmSglBooking.UltraTabPageControl6.None14'.", repo.FrmSglBooking.UltraTabPageControl6.None14Info, new RecordItemIndex(43));
            repo.FrmSglBooking.UltraTabPageControl6.None14.PressKeys(fareBasis);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.None15' at 16;10.", repo.FrmSglBooking.UltraTabPageControl6.None15Info, new RecordItemIndex(44));
            repo.FrmSglBooking.UltraTabPageControl6.None15.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$legPrice' with focus on 'FrmSglBooking.UltraTabPageControl6.None15'.", repo.FrmSglBooking.UltraTabPageControl6.None15Info, new RecordItemIndex(45));
            repo.FrmSglBooking.UltraTabPageControl6.None15.PressKeys(legPrice);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.ChkItineraireEscale' at 7;8.", repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireEscaleInfo, new RecordItemIndex(46));
            repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireEscale.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeur' at 5;6.", repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeurInfo, new RecordItemIndex(47));
            repo.FrmSglBooking.UltraTabPageControl61.ChkItineraireFumeur.Click("5;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.Open3' at 8;7.", repo.FrmSglBooking.UltraTabPageControl61.Open3Info, new RecordItemIndex(48));
            repo.FrmSglBooking.UltraTabPageControl61.Open3.Click("8;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.NDCContent' at 87;8.", repo.Bora.NDCContentInfo, new RecordItemIndex(49));
            repo.Bora.NDCContent.Click("87;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment' at 303;2.", repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegmentInfo, new RecordItemIndex(50));
            repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment.Click("303;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment' at 311;0.", repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegmentInfo, new RecordItemIndex(51));
            repo.FrmSglBooking.UltraTabPageControl61.UsplitDetailSegment.Click("311;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl6.PushButton' at 10;8.", repo.FrmSglBooking.UltraTabPageControl6.PushButtonInfo, new RecordItemIndex(52));
            repo.FrmSglBooking.UltraTabPageControl6.PushButton.Click("10;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
