///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createTarifs2 recording.
    /// </summary>
    [TestModule("84fc4894-669d-403f-8704-2ed07057155e", ModuleType.Recording, 1)]
    public partial class createTarifs2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createTarifs2 instance = new createTarifs2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createTarifs2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createTarifs2 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable reasonCode.
        /// </summary>
        [TestVariable("54ef5a7c-c8b0-4873-a020-3ffeebfb858a")]
        public string reasonCode
        {
            get { return repo.reasonCode; }
            set { repo.reasonCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageTarifs' at 32;11.", repo.FrmSglBooking.TabPageTarifsInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageTarifs.Click("32;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown' at 16;7.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDownInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown.Click("16;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions' at 53;6.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.Click("53;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissionsInfo, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.Open1' at 6;5.", repo.FrmSglBooking.UltraTabPageControl21.Open1Info, new RecordItemIndex(4));
            repo.FrmSglBooking.UltraTabPageControl21.Open1.Click("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ScrollingRegion1' at 130;7.", repo.Bora.ScrollingRegion1Info, new RecordItemIndex(5));
            repo.Bora.ScrollingRegion1.Click("130;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ComposanteTarifaire' at 305;97.", repo.FrmSglBooking.UltraTabPageControl2.ComposanteTarifaireInfo, new RecordItemIndex(6));
            repo.FrmSglBooking.UltraTabPageControl2.ComposanteTarifaire.Click("305;97");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown2' at 12;8.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown2Info, new RecordItemIndex(7));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown2.Click("12;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2' at 99;7.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2Info, new RecordItemIndex(8));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2.Click("99;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2Info, new RecordItemIndex(9));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions2.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None' at 118;8.", repo.FrmSglBooking.UltraTabPageControl2.NoneInfo, new RecordItemIndex(10));
            repo.FrmSglBooking.UltraTabPageControl2.None.Click("118;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.None'.", repo.FrmSglBooking.UltraTabPageControl2.NoneInfo, new RecordItemIndex(11));
            repo.FrmSglBooking.UltraTabPageControl2.None.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.ButtonDropDown3' at 18;9.", repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown3Info, new RecordItemIndex(12));
            repo.FrmSglBooking.UltraTabPageControl2.ButtonDropDown3.Click("18;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3' at 124;6.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3Info, new RecordItemIndex(13));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3.Click("124;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3'.", repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3Info, new RecordItemIndex(14));
            repo.FrmSglBooking.UltraTabPageControl2.EmbeddableTextBoxWithUIPermissions3.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl2.None1' at 129;8.", repo.FrmSglBooking.UltraTabPageControl2.None1Info, new RecordItemIndex(15));
            repo.FrmSglBooking.UltraTabPageControl2.None1.Click("129;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl2.None1'.", repo.FrmSglBooking.UltraTabPageControl2.None1Info, new RecordItemIndex(16));
            repo.FrmSglBooking.UltraTabPageControl2.None1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl21.Open2' at 7;9.", repo.FrmSglBooking.UltraTabPageControl21.Open2Info, new RecordItemIndex(17));
            repo.FrmSglBooking.UltraTabPageControl21.Open2.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Bora.ListItem' at 129;9.", repo.Bora.ListItemInfo, new RecordItemIndex(18));
            repo.Bora.ListItem.Click("129;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
