///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BoraTestEspaceVenteDDT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createMarge2 recording.
    /// </summary>
    [TestModule("0e77bb7c-50a2-460e-a15d-dac98f7274a2", ModuleType.Recording, 1)]
    public partial class createMarge2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BoraTestEspaceVenteDDTRepository repository.
        /// </summary>
        public static BoraTestEspaceVenteDDTRepository repo = BoraTestEspaceVenteDDTRepository.Instance;

        static createMarge2 instance = new createMarge2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createMarge2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createMarge2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.TabPageMarge' at 29;9.", repo.FrmSglBooking.TabPageMargeInfo, new RecordItemIndex(0));
            repo.FrmSglBooking.TabPageMarge.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.ButtonDropDown' at 17;9.", repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDownInfo, new RecordItemIndex(1));
            repo.FrmSglBooking.UltraTabPageControl5.ButtonDropDown.Click("17;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1' at 87;6.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(2));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.Click("87;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1'.", repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1Info, new RecordItemIndex(3));
            repo.FrmSglBooking.UltraTabPageControl5.EmbeddableTextBoxWithUIPermissions1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
